const storeMapping = {
  'AAQ': { storeName: 'AAQ', mallHS: 'Mall', state: 'Gujarat' },
  'AAS': { storeName: 'AAS', mallHS: 'Mall', state: 'Gujarat' },
  'ABD': { storeName: 'ABD', mallHS: 'High-Street', state: 'Gujarat' },
  'ABP': { storeName: 'ABP', mallHS: 'High-Street', state: 'Gujarat' },
  'ABQ': { storeName: 'ABQ', mallHS: 'High-Street', state: 'Gujarat' },
  'ABR': { storeName: 'ABR', mallHS: 'High-Street', state: 'Gujarat' },
  'ABV': { storeName: 'ABV', mallHS: 'High-Street', state: 'Bihar' },
  'ACQ': { storeName: 'ACQ', mallHS: 'High-Street', state: 'Haryana' },
  'ADM': { storeName: 'ADM', mallHS: 'High-Street', state: 'Gujarat' },
  'ADQ': { storeName: 'ADQ', mallHS: 'High-Street', state: 'Gujarat' },
  'ADS': { storeName: 'ADS', mallHS: 'High-Street', state: 'Gujarat' },
  'AGL': { storeName: 'AGL', mallHS: 'High-Street', state: 'Odisha' },
  'AGM': { storeName: 'AGM', mallHS: 'High-Street', state: 'Punjab' },
  'AGQ': { storeName: 'AGQ', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'AGT': { storeName: 'AGT', mallHS: 'High-Street', state: 'Tripura' },
  'AGV': { storeName: 'AGV', mallHS: 'High-Street', state: 'Maharashtra' },
  'AHM': { storeName: 'AHM', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'AJM': { storeName: 'AJM', mallHS: 'High-Street', state: 'Rajasthan' },
  'AJR': { storeName: 'AJR', mallHS: 'High-Street', state: 'Rajasthan' },
  'AJS': { storeName: 'AJS', mallHS: 'High-Street', state: 'Rajasthan' },
  'ALA': { storeName: 'ALA', mallHS: 'High-Street', state: 'Haryana' },
  'ALH': { storeName: 'ALH', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'ALM': { storeName: 'ALM', mallHS: 'High-Street', state: 'Haryana' },
  'ALQ': { storeName: 'ALQ', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'ALR': { storeName: 'ALR', mallHS: 'High-Street', state: 'Rajasthan' },
  'ALV': { storeName: 'ALV', mallHS: 'High-Street', state: 'Rajasthan' },
  'AMN': { storeName: 'AMN', mallHS: 'High-Street', state: 'Gujarat' },
  'AMQ': { storeName: 'AMQ', mallHS: 'Mall', state: 'Punjab' },
  'AMR': { storeName: 'AMR', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'AMT': { storeName: 'AMT', mallHS: 'Mall', state: 'Gujarat' },
  'AND': { storeName: 'AND', mallHS: 'High-Street', state: 'Maharashtra' },
  'ANQ': { storeName: 'ANQ', mallHS: 'High-Street', state: 'Gujarat' },
  'ANV': { storeName: 'ANV', mallHS: 'High-Street', state: 'Maharashtra' },
  'AOQ': { storeName: 'AOQ', mallHS: 'High-Street', state: 'Gujarat' },
  'AOS': { storeName: 'AOS', mallHS: 'High-Street', state: 'Gujarat' },
  'APQ': { storeName: 'APQ', mallHS: 'Mall', state: 'Maharashtra' },
  'APV': { storeName: 'APV', mallHS: 'Mall', state: 'Maharashtra' },
  'ARA': { storeName: 'ARA', mallHS: 'Mall', state: 'Punjab' },
  'ARM': { storeName: 'ARM', mallHS: 'High-Street', state: 'Punjab' },
  'ARQ': { storeName: 'ARQ', mallHS: 'High-Street', state: 'Punjab' },
  'ARS': { storeName: 'ARS', mallHS: 'High-Street', state: 'Punjab' },
  'ASN': { storeName: 'ASN', mallHS: 'High-Street', state: 'West Bengal' },
  'AST': { storeName: 'AST', mallHS: 'High-Street', state: 'Gujarat' },
  'ATM': { storeName: 'ATM', mallHS: 'Mall', state: 'Punjab' },
  'ATS': { storeName: 'ATS', mallHS: 'Mall', state: 'Punjab' },
  'AUM': { storeName: 'AUM', mallHS: 'Mall', state: 'Maharashtra' },
  'AUP': { storeName: 'AUP', mallHS: 'Mall', state: 'Maharashtra' },
  'AUQ': { storeName: 'AUQ', mallHS: 'High-Street', state: 'Maharashtra' },
  'AUS': { storeName: 'AUS', mallHS: 'High-Street', state: 'Maharashtra' },
  'AUV': { storeName: 'AUV', mallHS: 'High-Street', state: 'Maharashtra' },
  'AVT': { storeName: 'AVT', mallHS: 'High-Street', state: 'Maharashtra' },
  'AWM': { storeName: 'AWM', mallHS: 'High-Street', state: 'Rajasthan' },
  'AZV': { storeName: 'AZV', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'B2Q': { storeName: 'B2Q', mallHS: 'Mall', state: 'Chhattisgarh' },
  'B3Q': { storeName: 'B3Q', mallHS: 'Mall', state: 'Karnataka' },
  'BAQ': { storeName: 'BAQ', mallHS: 'High-Street', state: 'Odisha' },
  'BAV': { storeName: 'BAV', mallHS: 'Mall', state: 'Madhya Pradesh' },
  'BBM': { storeName: 'BBM', mallHS: 'Mall', state: 'Gujarat' },
  'BBQ': { storeName: 'BBQ', mallHS: 'Mall', state: 'Gujarat' },
  'BBR': { storeName: 'BBR', mallHS: 'Mall', state: 'Odisha' },
  'BCC': { storeName: 'BCC', mallHS: 'Mall', state: 'Karnataka' },
  'BCM': { storeName: 'BCM', mallHS: 'High-Street', state: 'Chhattisgarh' },
  'BCQ': { storeName: 'BCQ', mallHS: 'Mall', state: 'Karnataka' },
  'BCV': { storeName: 'BCV', mallHS: 'Mall', state: 'Gujarat' },
  'BDR': { storeName: 'BDR', mallHS: 'High-Street', state: 'Karnataka' },
  'BFM': { storeName: 'BFM', mallHS: 'Mall', state: 'Karnataka' },
  'BFQ': { storeName: 'BFQ', mallHS: 'Mall', state: 'Karnataka' },
  'BFS': { storeName: 'BFS', mallHS: 'Mall', state: 'Karnataka' },
  'BGB': { storeName: 'BGB', mallHS: 'High-Street', state: 'Karnataka' },
  'BGL': { storeName: 'BGL', mallHS: 'High-Street', state: 'Karnataka' },
  'BGM': { storeName: 'BGM', mallHS: 'High-Street', state: 'Karnataka' },
  'BGQ': { storeName: 'BGQ', mallHS: 'High-Street', state: 'Karnataka' },
  'BHJ': { storeName: 'BHJ', mallHS: 'High-Street', state: 'Gujarat' },
  'BHL': { storeName: 'BHL', mallHS: 'Mall', state: 'Chhattisgarh' },
  'BHR': { storeName: 'BHR', mallHS: 'High-Street', state: 'Karnataka' },
  'BHU': { storeName: 'BHU', mallHS: 'High-Street', state: 'Odisha' },
  'BIN': { storeName: 'BIN', mallHS: 'High-Street', state: 'Karnataka' },
  'BIQ': { storeName: 'BIQ', mallHS: 'High-Street', state: 'Karnataka' },
  'BIV': { storeName: 'BIV', mallHS: 'High-Street', state: 'Karnataka' },
  'BJM': { storeName: 'BJM', mallHS: 'High-Street', state: 'Karnataka' },
  'BJQ': { storeName: 'BJQ', mallHS: 'High-Street', state: 'Karnataka' },
  'BJV': { storeName: 'BJV', mallHS: 'Mall', state: 'Karnataka' },
  'BJY': { storeName: 'BJY', mallHS: 'High-Street', state: 'Karnataka' },
  'BKM': { storeName: 'BKM', mallHS: 'Mall', state: 'Karnataka' },
  'BKQ': { storeName: 'BKQ', mallHS: 'High-Street', state: 'Karnataka' },
  'BKR': { storeName: 'BKR', mallHS: 'High-Street', state: 'Rajasthan' },
  'BLG': { storeName: 'BLG', mallHS: 'High-Street', state: 'Karnataka' },
  'BLL': { storeName: 'BLL', mallHS: 'High-Street', state: 'Karnataka' },
  'BLM': { storeName: 'BLM', mallHS: 'High-Street', state: 'Karnataka' },
  'BLP': { storeName: 'BLP', mallHS: 'High-Street', state: 'Maharashtra' },
  'BLQ': { storeName: 'BLQ', mallHS: 'Mall', state: 'Karnataka' },
  'BLU': { storeName: 'BLU', mallHS: 'Mall', state: 'Karnataka' },
  'BLV': { storeName: 'BLV', mallHS: 'High-Street', state: 'Karnataka' },
  'BMM': { storeName: 'BMM', mallHS: 'Mall', state: 'Karnataka' },
  'BMS': { storeName: 'BMS', mallHS: 'Mall', state: 'Karnataka' },
  'BNL': { storeName: 'BNL', mallHS: 'High-Street', state: 'Punjab' },
  'BNM': { storeName: 'BNM', mallHS: 'High-Street', state: 'Punjab' },
  'BNQ': { storeName: 'BNQ', mallHS: 'High-Street', state: 'Punjab' },
  'BNR': { storeName: 'BNR', mallHS: 'High-Street', state: 'Gujarat' },
  'BOM': { storeName: 'BOM', mallHS: 'Mall', state: 'Karnataka' },
  'BOQ': { storeName: 'BOQ', mallHS: 'Mall', state: 'Karnataka' },
  'BPL': { storeName: 'BPL', mallHS: 'High-Street', state: 'Madhya Pradesh' },
  'BPM': { storeName: 'BPM', mallHS: 'Mall', state: 'Madhya Pradesh' },
  'BPQ': { storeName: 'BPQ', mallHS: 'Mall', state: 'Madhya Pradesh' },
  'BPR': { storeName: 'BPR', mallHS: 'High-Street', state: 'Madhya Pradesh' },
  'BPS': { storeName: 'BPS', mallHS: 'Mall', state: 'Madhya Pradesh' },
  'BQM': { storeName: 'BQM', mallHS: 'High-Street', state: 'Karnataka' },
  'BQQ': { storeName: 'BQQ', mallHS: 'High-Street', state: 'Karnataka' },
  'BRD': { storeName: 'BRD', mallHS: 'High-Street', state: 'Gujarat' },
  'BRH': { storeName: 'BRH', mallHS: 'High-Street', state: 'Gujarat' },
  'BRM': { storeName: 'BRM', mallHS: 'High-Street', state: 'Gujarat' },
  'BRQ': { storeName: 'BRQ', mallHS: 'High-Street', state: 'Gujarat' },
  'BRS': { storeName: 'BRS', mallHS: 'High-Street', state: 'Gujarat' },
  'BRV': { storeName: 'BRV', mallHS: 'High-Street', state: 'Gujarat' },
  'BRZ': { storeName: 'BRZ', mallHS: 'Mall', state: 'Karnataka' },
  'BSM': { storeName: 'BSM', mallHS: 'Mall', state: 'Karnataka' },
  'BSP': { storeName: 'BSP', mallHS: 'Mall', state: 'Chhattisgarh' },
  'BSQ': { storeName: 'BSQ', mallHS: 'High-Street', state: 'Karnataka' },
  'BSS': { storeName: 'BSS', mallHS: 'High-Street', state: 'Karnataka' },
  'BST': { storeName: 'BST', mallHS: 'Shop-N-Shop', state: 'Karnataka' },
  'BTD': { storeName: 'BTD', mallHS: 'High-Street', state: 'Punjab' },
  'BTM': { storeName: 'BTM', mallHS: 'High-Street', state: 'Punjab' },
  'BTQ': { storeName: 'BTQ', mallHS: 'High-Street', state: 'Punjab' },
  'BVC': { storeName: 'BVC', mallHS: 'Mall', state: 'Karnataka' },
  'BVM': { storeName: 'BVM', mallHS: 'High-Street', state: 'Madhya Pradesh' },
  'BVQ': { storeName: 'BVQ', mallHS: 'Mall', state: 'Karnataka' },
  'BVS': { storeName: 'BVS', mallHS: 'Mall', state: 'Karnataka' },
  'BWM': { storeName: 'BWM', mallHS: 'High-Street', state: 'Odisha' },
  'BWQ': { storeName: 'BWQ', mallHS: 'High-Street', state: 'Karnataka' },
  'BXM': { storeName: 'BXM', mallHS: 'High-Street', state: 'Odisha' },
  'BXQ': { storeName: 'BXQ', mallHS: 'High-Street', state: 'Odisha' },
  'BYM': { storeName: 'BYM', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'BYQ': { storeName: 'BYQ', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'BYS': { storeName: 'BYS', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'BZM': { storeName: 'BZM', mallHS: 'High-Street', state: 'Karnataka' },
  'BZQ': { storeName: 'BZQ', mallHS: 'Mall', state: 'Karnataka' },
  'CAM': { storeName: 'CAM', mallHS: 'Mall', state: 'West Bengal' },
  'CAP': { storeName: 'CAP', mallHS: 'Mall', state: 'West Bengal' },
  'CAQ': { storeName: 'CAQ', mallHS: 'Mall', state: 'West Bengal' },
  'CAV': { storeName: 'CAV', mallHS: 'Mall', state: 'West Bengal' },
  'CBM': { storeName: 'CBM', mallHS: 'High-Street', state: 'Maharashtra' },
  'CBQ': { storeName: 'CBQ', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'CCK': { storeName: 'CCK', mallHS: 'Mall', state: 'West Bengal' },
  'CCM': { storeName: 'CCM', mallHS: 'Mall', state: 'West Bengal' },
  'CCQ': { storeName: 'CCQ', mallHS: 'Mall', state: 'West Bengal' },
  'CCR': { storeName: 'CCR', mallHS: 'Mall', state: 'West Bengal' },
  'CCU': { storeName: 'CCU', mallHS: 'High-Street', state: 'West Bengal' },
  'CDM': { storeName: 'CDM', mallHS: 'High-Street', state: 'Chandigarh' },
  'CDQ': { storeName: 'CDQ', mallHS: 'High-Street', state: 'Chandigarh' },
  'CFM': { storeName: 'CFM', mallHS: 'Mall', state: 'Tamil Nadu' },
  'CFQ': { storeName: 'CFQ', mallHS: 'Mall', state: 'Tamil Nadu' },
  'CFV': { storeName: 'CFV', mallHS: 'Mall', state: 'Tamil Nadu' },
  'CGM': { storeName: 'CGM', mallHS: 'Mall', state: 'Kerala' },
  'CGQ': { storeName: 'CGQ', mallHS: 'Mall', state: 'Kerala' },
  'CGV': { storeName: 'CGV', mallHS: 'Mall', state: 'Kerala' },
  'CHM': { storeName: 'CHM', mallHS: 'Mall', state: 'Kerala' },
  'CHQ': { storeName: 'CHQ', mallHS: 'Mall', state: 'Chandigarh' },
  'CHS': { storeName: 'CHS', mallHS: 'Mall', state: 'Chandigarh' },
  'CHW': { storeName: 'CHW', mallHS: 'High-Street', state: 'Madhya Pradesh' },
  'CIL': { storeName: 'CIL', mallHS: 'High-Street', state: 'Kerala' },
  'CIQ': { storeName: 'CIQ', mallHS: 'Mall', state: 'Kerala' },
  'CIS': { storeName: 'CIS', mallHS: 'Mall', state: 'Kerala' },
  'CKP': { storeName: 'CKP', mallHS: 'High-Street', state: 'West Bengal' },
  'CLB': { storeName: 'CLB', mallHS: 'High-Street', state: 'Maharashtra' },
  'CLM': { storeName: 'CLM', mallHS: 'High-Street', state: 'West Bengal' },
  'CLQ': { storeName: 'CLQ', mallHS: 'Mall', state: 'West Bengal' },
  'CMM': { storeName: 'CMM', mallHS: 'Mall', state: 'West Bengal' },
  'CMQ': { storeName: 'CMQ', mallHS: 'Mall', state: 'West Bengal' },
  'CMS': { storeName: 'CMS', mallHS: 'Mall', state: 'West Bengal' },
  'CMV': { storeName: 'CMV', mallHS: 'High-Street', state: 'Maharashtra' },
  'CNB': { storeName: 'CNB', mallHS: 'Mall', state: 'West Bengal' },
  'COM': { storeName: 'COM', mallHS: 'Mall', state: 'Chandigarh' },
  'COQ': { storeName: 'COQ', mallHS: 'Mall', state: 'West Bengal' },
  'CPM': { storeName: 'CPM', mallHS: 'Mall', state: 'Tamil Nadu' },
  'CPQ': { storeName: 'CPQ', mallHS: 'Mall', state: 'Tamil Nadu' },
  'CPS': { storeName: 'CPS', mallHS: 'Mall', state: 'Tamil Nadu' },
  'CRB': { storeName: 'CRB', mallHS: 'Mall', state: 'West Bengal' },
  'CSC': { storeName: 'CSC', mallHS: 'Mall', state: 'West Bengal' },
  'CSD': { storeName: 'CSD', mallHS: 'High-Street', state: 'Chandigarh' },
  'CSM': { storeName: 'CSM', mallHS: 'Mall', state: 'West Bengal' },
  'CTK': { storeName: 'CTK', mallHS: 'High-Street', state: 'Odisha' },
  'CTM': { storeName: 'CTM', mallHS: 'High-Street', state: 'Kerala' },
  'CTQ': { storeName: 'CTQ', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'CTR': { storeName: 'CTR', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'CWT': { storeName: 'CWT', mallHS: 'High-Street', state: 'Maharashtra' },
  'DAL': { storeName: 'DAL', mallHS: 'Airport', state: 'Delhi' },
  'DAM': { storeName: 'DAM', mallHS: 'Mall', state: 'Delhi' },
  'DBR': { storeName: 'DBR', mallHS: 'High-Street', state: 'Assam' },
  'DCB': { storeName: 'DCB', mallHS: 'Mall', state: 'Jharkhand' },
  'DCM': { storeName: 'DCM', mallHS: 'Mall', state: 'Jharkhand' },
  'DDM': { storeName: 'DDM', mallHS: 'High-Street', state: 'Uttarakhand' },
  'DDO': { storeName: 'DDO', mallHS: 'High-Street', state: 'Uttarakhand' },
  'DDQ': { storeName: 'DDQ', mallHS: 'Mall', state: 'Uttarakhand' },
  'DDR': { storeName: 'DDR', mallHS: 'High-Street', state: 'Maharashtra' },
  'DDU': { storeName: 'DDU', mallHS: 'Mall', state: 'Uttarakhand' },
  'DEM': { storeName: 'DEM', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'DEQ': { storeName: 'DEQ', mallHS: 'Mall', state: 'Delhi' },
  'DGK': { storeName: 'DGK', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'DGM': { storeName: 'DGM', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'DGZ': { storeName: 'DGZ', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'DJQ': { storeName: 'DJQ', mallHS: 'High-Street', state: 'Delhi' },
  'DKM': { storeName: 'DKM', mallHS: 'Mall', state: 'Delhi' },
  'DKN': { storeName: 'DKN', mallHS: 'High-Street', state: 'Delhi' },
  'DLK': { storeName: 'DLK', mallHS: 'High-Street', state: 'Delhi' },
  'DLN': { storeName: 'DLN', mallHS: 'Mall', state: 'Delhi' },
  'DLQ': { storeName: 'DLQ', mallHS: 'High-Street', state: 'Delhi' },
  'DMP': { storeName: 'DMP', mallHS: 'High-Street', state: 'Nagaland' },
  'DNQ': { storeName: 'DNQ', mallHS: 'High-Street', state: 'Uttarakhand' },
  'DPE': { storeName: 'DPE', mallHS: 'Mall', state: 'Maharashtra' },
  'DPQ': { storeName: 'DPQ', mallHS: 'Mall', state: 'Delhi' },
  'DPS': { storeName: 'DPS', mallHS: 'Mall', state: 'Delhi' },
  'DRM': { storeName: 'DRM', mallHS: 'Mall', state: 'Delhi' },
  'DRP': { storeName: 'DRP', mallHS: 'Mall', state: 'Delhi' },
  'DRQ': { storeName: 'DRQ', mallHS: 'High-Street', state: 'Delhi' },
  'DRS': { storeName: 'DRS', mallHS: 'Mall', state: 'Delhi' },
  'DSM': { storeName: 'DSM', mallHS: 'High-Street', state: 'Delhi' },
  'DSQ': { storeName: 'DSQ', mallHS: 'Mall', state: 'Delhi' },
  'DSX': { storeName: 'DSX', mallHS: 'High-Street', state: 'Delhi' },
  'DTM': { storeName: 'DTM', mallHS: 'High-Street', state: 'Maharashtra' },
  'DUQ': { storeName: 'DUQ', mallHS: 'Mall', state: 'Uttarakhand' },
  'DVQ': { storeName: 'DVQ', mallHS: 'Mall', state: 'Delhi' },
  'DWM': { storeName: 'DWM', mallHS: 'Mall', state: 'Delhi' },
  'DWQ': { storeName: 'DWQ', mallHS: 'Mall', state: 'Delhi' },
  'DXL': { storeName: 'DXL', mallHS: 'High-Street', state: 'Delhi' },
  'DZM': { storeName: 'DZM', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'DZP': { storeName: 'DZP', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'DZQ': { storeName: 'DZQ', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'EBQ': { storeName: 'EBQ', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'ERD': { storeName: 'ERD', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'FCL': { storeName: 'FCL', mallHS: 'Mall', state: 'West Bengal' },
  'FCQ': { storeName: 'FCQ', mallHS: 'Mall', state: 'West Bengal' },
  'FGM': { storeName: 'FGM', mallHS: 'Mall', state: 'Karnataka' },
  'FMQ': { storeName: 'FMQ', mallHS: 'Mall', state: 'Karnataka' },
  'FMS': { storeName: 'FMS', mallHS: 'Mall', state: 'Karnataka' },
  'FSM': { storeName: 'FSM', mallHS: 'Mall', state: 'Karnataka' },
  'FSQ': { storeName: 'FSQ', mallHS: 'Mall', state: 'Karnataka' },
  'FSS': { storeName: 'FSS', mallHS: 'Mall', state: 'Karnataka' },
  'FX9': { storeName: 'FX9', mallHS: 'Mall', state: 'Tamil Nadu' },
  'GAS': { storeName: 'GAS', mallHS: 'Mall', state: 'Haryana' },
  'GBQ': { storeName: 'GBQ', mallHS: 'Mall', state: 'Sikkim' },
  'GCM': { storeName: 'GCM', mallHS: 'Mall', state: 'Assam' },
  'GCQ': { storeName: 'GCQ', mallHS: 'Mall', state: 'Haryana' },
  'GDB': { storeName: 'GDB', mallHS: 'Mall', state: 'Madhya Pradesh' },
  'GDM': { storeName: 'GDM', mallHS: 'Mall', state: 'Haryana' },
  'GDQ': { storeName: 'GDQ', mallHS: 'Mall', state: 'Haryana' },
  'GEQ': { storeName: 'GEQ', mallHS: 'Mall', state: 'Haryana' },
  'GGM': { storeName: 'GGM', mallHS: 'High-Street', state: 'Rajasthan' },
  'GGN': { storeName: 'GGN', mallHS: 'High-Street', state: 'Rajasthan' },
  'GGQ': { storeName: 'GGQ', mallHS: 'High-Street', state: 'Rajasthan' },
  'GGV': { storeName: 'GGV', mallHS: 'High-Street', state: 'Rajasthan' },
  'GHD': { storeName: 'GHD', mallHS: 'High-Street', state: 'Gujarat' },
  'GHM': { storeName: 'GHM', mallHS: 'High-Street', state: 'Gujarat' },
  'GIQ': { storeName: 'GIQ', mallHS: 'High-Street', state: 'Gujarat' },
  'GKM': { storeName: 'GKM', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'GKP': { storeName: 'GKP', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'GKQ': { storeName: 'GKQ', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'GKV': { storeName: 'GKV', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'GLM': { storeName: 'GLM', mallHS: 'Mall', state: 'Karnataka' },
  'GLQ': { storeName: 'GLQ', mallHS: 'Mall', state: 'Karnataka' },
  'GMM': { storeName: 'GMM', mallHS: 'Mall', state: 'Haryana' },
  'GMQ': { storeName: 'GMQ', mallHS: 'High-Street', state: 'Goa' },
  'GMS': { storeName: 'GMS', mallHS: 'Mall', state: 'Haryana' },
  'GNM': { storeName: 'GNM', mallHS: 'High-Street', state: 'Andhra Pradesh' },
  'GNQ': { storeName: 'GNQ', mallHS: 'High-Street', state: 'Andhra Pradesh' },
  'GNT': { storeName: 'GNT', mallHS: 'High-Street', state: 'Sikkim' },
  'GOA': { storeName: 'GOA', mallHS: 'High-Street', state: 'Goa' },
  'GOM': { storeName: 'GOM', mallHS: 'High-Street', state: 'Goa' },
  'GOQ': { storeName: 'GOQ', mallHS: 'High-Street', state: 'Goa' },
  'GOR': { storeName: 'GOR', mallHS: 'Mall', state: 'Maharashtra' },
  'GRD': { storeName: 'GRD', mallHS: 'High-Street', state: 'Maharashtra' },
  'GRM': { storeName: 'GRM', mallHS: 'High-Street', state: 'Maharashtra' },
  'GRQ': { storeName: 'GRQ', mallHS: 'Mall', state: 'Haryana' },
  'GTK': { storeName: 'GTK', mallHS: 'High-Street', state: 'Maharashtra' },
  'GTM': { storeName: 'GTM', mallHS: 'Mall', state: 'Maharashtra' },
  'GTQ': { storeName: 'GTQ', mallHS: 'Mall', state: 'Maharashtra' },
  'GTR': { storeName: 'GTR', mallHS: 'High-Street', state: 'Andhra Pradesh' },
  'GTS': { storeName: 'GTS', mallHS: 'Mall', state: 'Maharashtra' },
  'GUH': { storeName: 'GUH', mallHS: 'High-Street', state: 'Assam' },
  'GUL': { storeName: 'GUL', mallHS: 'High-Street', state: 'Karnataka' },
  'GUM': { storeName: 'GUM', mallHS: 'High-Street', state: 'Assam' },
  'GUN': { storeName: 'GUN', mallHS: 'Mall', state: 'Assam' },
  'GUQ': { storeName: 'GUQ', mallHS: 'High-Street', state: 'Assam' },
  'GUV': { storeName: 'GUV', mallHS: 'High-Street', state: 'Karnataka' },
  'GUZ': { storeName: 'GUZ', mallHS: 'High-Street', state: 'Assam' },
  'GVM': { storeName: 'GVM', mallHS: 'Mall', state: 'Sikkim' },
  'GVQ': { storeName: 'GVQ', mallHS: 'Mall', state: 'Goa' },
  'GWM': { storeName: 'GWM', mallHS: 'Mall', state: 'Madhya Pradesh' },
  'GWR': { storeName: 'GWR', mallHS: 'High-Street', state: 'Madhya Pradesh' },
  'GWV': { storeName: 'GWV', mallHS: 'High-Street', state: 'Andhra Pradesh' },
  'GZQ': { storeName: 'GZQ', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'HAM': { storeName: 'HAM', mallHS: 'Airport', state: 'Telangana' },
  'HAQ': { storeName: 'HAQ', mallHS: 'Airport', state: 'Telangana' },
  'HAV': { storeName: 'HAV', mallHS: 'High-Street', state: 'Telangana' },
  'HBQ': { storeName: 'HBQ', mallHS: 'High-Street', state: 'Telangana' },
  'HBS': { storeName: 'HBS', mallHS: 'High-Street', state: 'Telangana' },
  'HBU': { storeName: 'HBU', mallHS: 'Mall', state: 'Karnataka' },
  'HBV': { storeName: 'HBV', mallHS: 'High-Street', state: 'Telangana' },
  'HCM': { storeName: 'HCM', mallHS: 'Mall', state: 'Telangana' },
  'HCQ': { storeName: 'HCQ', mallHS: 'Mall', state: 'Telangana' },
  'HCS': { storeName: 'HCS', mallHS: 'Mall', state: 'Telangana' },
  'HCV': { storeName: 'HCV', mallHS: 'High-Street', state: 'Telangana' },
  'HDM': { storeName: 'HDM', mallHS: 'High-Street', state: 'Telangana' },
  'HDQ': { storeName: 'HDQ', mallHS: 'Mall', state: 'Telangana' },
  'HDR': { storeName: 'HDR', mallHS: 'High-Street', state: 'Uttarakhand' },
  'HDS': { storeName: 'HDS', mallHS: 'Mall', state: 'Telangana' },
  'HDV': { storeName: 'HDV', mallHS: 'High-Street', state: 'Karnataka' },
  'HFM': { storeName: 'HFM', mallHS: 'Mall', state: 'Telangana' },
  'HFQ': { storeName: 'HFQ', mallHS: 'Mall', state: 'Telangana' },
  'HFV': { storeName: 'HFV', mallHS: 'Mall', state: 'Telangana' },
  'HHP': { storeName: 'HHP', mallHS: 'High-Street', state: 'Punjab' },
  'HHV': { storeName: 'HHV', mallHS: 'High-Street', state: 'Telangana' },
  'HIQ': { storeName: 'HIQ', mallHS: 'Mall', state: 'Telangana' },
  'HJM': { storeName: 'HJM', mallHS: 'High-Street', state: 'Telangana' },
  'HKM': { storeName: 'HKM', mallHS: 'High-Street', state: 'Telangana' },
  'HKV': { storeName: 'HKV', mallHS: 'High-Street', state: 'Telangana' },
  'HLD': { storeName: 'HLD', mallHS: 'High-Street', state: 'Uttarakhand' },
  'HLV': { storeName: 'HLV', mallHS: 'High-Street', state: 'Telangana' },
  'HMV': { storeName: 'HMV', mallHS: 'High-Street', state: 'Telangana' },
  'HNG': { storeName: 'HNG', mallHS: 'High-Street', state: 'Rajasthan' },
  'HNM': { storeName: 'HNM', mallHS: 'High-Street', state: 'Telangana' },
  'HNQ': { storeName: 'HNQ', mallHS: 'High-Street', state: 'Telangana' },
  'HOM': { storeName: 'HOM', mallHS: 'Mall', state: 'Telangana' },
  'HPM': { storeName: 'HPM', mallHS: 'High-Street', state: 'Telangana' },
  'HRM': { storeName: 'HRM', mallHS: 'High-Street', state: 'Telangana' },
  'HRQ': { storeName: 'HRQ', mallHS: 'High-Street', state: 'Telangana' },
  'HSM': { storeName: 'HSM', mallHS: 'High-Street', state: 'Telangana' },
  'HSQ': { storeName: 'HSQ', mallHS: 'High-Street', state: 'Telangana' },
  'HSR': { storeName: 'HSR', mallHS: 'High-Street', state: 'Haryana' },
  'HSV': { storeName: 'HSV', mallHS: 'High-Street', state: 'Telangana' },
  'HTM': { storeName: 'HTM', mallHS: 'High-Street', state: 'Telangana' },
  'HTQ': { storeName: 'HTQ', mallHS: 'High-Street', state: 'Telangana' },
  'HTV': { storeName: 'HTV', mallHS: 'High-Street', state: 'Telangana' },
  'HUM': { storeName: 'HUM', mallHS: 'Mall', state: 'Karnataka' },
  'HUQ': { storeName: 'HUQ', mallHS: 'Mall', state: 'Karnataka' },
  'HUV': { storeName: 'HUV', mallHS: 'Mall', state: 'Karnataka' },
  'HYD': { storeName: 'HYD', mallHS: 'High-Street', state: 'Telangana' },
  'IBM': { storeName: 'IBM', mallHS: 'Mall', state: 'Maharashtra' },
  'IBQ': { storeName: 'IBQ', mallHS: 'Mall', state: 'Maharashtra' },
  'IDQ': { storeName: 'IDQ', mallHS: 'High-Street', state: 'Madhya Pradesh' },
  'IDV': { storeName: 'IDV', mallHS: 'High-Street', state: 'Madhya Pradesh' },
  'IFM': { storeName: 'IFM', mallHS: 'Mall', state: 'Maharashtra' },
  'IKV': { storeName: 'IKV', mallHS: 'Mall', state: 'Maharashtra' },
  'IMM': { storeName: 'IMM', mallHS: 'High-Street', state: 'Madhya Pradesh' },
  'IMP': { storeName: 'IMP', mallHS: 'High-Street', state: 'Manipur' },
  'IMQ': { storeName: 'IMQ', mallHS: 'Mall', state: 'Maharashtra' },
  'IMS': { storeName: 'IMS', mallHS: 'Mall', state: 'Maharashtra' },
  'IPQ': { storeName: 'IPQ', mallHS: 'High-Street', state: 'Manipur' },
  'ISM': { storeName: 'ISM', mallHS: 'High-Street', state: 'Madhya Pradesh' },
  'ISQ': { storeName: 'ISQ', mallHS: 'Mall', state: 'Madhya Pradesh' },
  'ISS': { storeName: 'ISS', mallHS: 'High-Street', state: 'Madhya Pradesh' },
  'ITM': { storeName: 'ITM', mallHS: 'High-Street', state: 'Arunachal Pradesh' },
  'ITN': { storeName: 'ITN', mallHS: 'High-Street', state: 'Arunachal Pradesh' },
  'ITQ': { storeName: 'ITQ', mallHS: 'High-Street', state: 'Arunachal Pradesh' },
  'ITS': { storeName: 'ITS', mallHS: 'Mall', state: 'Madhya Pradesh' },
  'JAM': { storeName: 'JAM', mallHS: 'High-Street', state: 'Punjab' },
  'JAQ': { storeName: 'JAQ', mallHS: 'High-Street', state: 'Gujarat' },
  'JBL': { storeName: 'JBL', mallHS: 'Mall', state: 'Madhya Pradesh' },
  'JBM': { storeName: 'JBM', mallHS: 'High-Street', state: 'Madhya Pradesh' },
  'JBQ': { storeName: 'JBQ', mallHS: 'Mall', state: 'Madhya Pradesh' },
  'JCM': { storeName: 'JCM', mallHS: 'High-Street', state: 'Rajasthan' },
  'JCQ': { storeName: 'JCQ', mallHS: 'High-Street', state: 'Rajasthan' },
  'JDH': { storeName: 'JDH', mallHS: 'High-Street', state: 'Rajasthan' },
  'JDM': { storeName: 'JDM', mallHS: 'High-Street', state: 'Rajasthan' },
  'JDV': { storeName: 'JDV', mallHS: 'High-Street', state: 'Jharkhand' },
  'JGM': { storeName: 'JGM', mallHS: 'High-Street', state: 'Assam' },
  'JHM': { storeName: 'JHM', mallHS: 'High-Street', state: 'Jharkhand' },
  'JHQ': { storeName: 'JHQ', mallHS: 'High-Street', state: 'Jharkhand' },
  'JHR': { storeName: 'JHR', mallHS: 'High-Street', state: 'Jharkhand' },
  'JHT': { storeName: 'JHT', mallHS: 'High-Street', state: 'Assam' },
  'JIM': { storeName: 'JIM', mallHS: 'High-Street', state: 'Rajasthan' },
  'JLQ': { storeName: 'JLQ', mallHS: 'High-Street', state: 'Punjab' },
  'JMD': { storeName: 'JMD', mallHS: 'High-Street', state: 'Punjab' },
  'JMM': { storeName: 'JMM', mallHS: 'High-Street', state: 'Gujarat' },
  'JMN': { storeName: 'JMN', mallHS: 'High-Street', state: 'Gujarat' },
  'JMQ': { storeName: 'JMQ', mallHS: 'Mall', state: 'Rajasthan' },
  'JMS': { storeName: 'JMS', mallHS: 'High-Street', state: 'Rajasthan' },
  'JMW': { storeName: 'JMW', mallHS: 'Mall', state: 'Jammu And Kashmir' },
  'JNQ': { storeName: 'JNQ', mallHS: 'Mall', state: 'Jharkhand' },
  'JOM': { storeName: 'JOM', mallHS: 'High-Street', state: 'Maharashtra' },
  'JPM': { storeName: 'JPM', mallHS: 'Mall', state: 'Rajasthan' },
  'JPQ': { storeName: 'JPQ', mallHS: 'High-Street', state: 'Rajasthan' },
  'JPR': { storeName: 'JPR', mallHS: 'High-Street', state: 'Rajasthan' },
  'JPS': { storeName: 'JPS', mallHS: 'High-Street', state: 'Rajasthan' },
  'JPV': { storeName: 'JPV', mallHS: 'Mall', state: 'Rajasthan' },
  'JRM': { storeName: 'JRM', mallHS: 'High-Street', state: 'Rajasthan' },
  'JRQ': { storeName: 'JRQ', mallHS: 'Mall', state: 'Rajasthan' },
  'JRR': { storeName: 'JRR', mallHS: 'High-Street', state: 'Rajasthan' },
  'JSM': { storeName: 'JSM', mallHS: 'Mall', state: 'Rajasthan' },
  'JSQ': { storeName: 'JSQ', mallHS: 'Mall', state: 'Madhya Pradesh' },
  'JTQ': { storeName: 'JTQ', mallHS: 'High-Street', state: 'Rajasthan' },
  'JUQ': { storeName: 'JUQ', mallHS: 'Mall', state: 'Jammu And Kashmir' },
  'JWQ': { storeName: 'JWQ', mallHS: 'Mall', state: 'Rajasthan' },
  'JWT': { storeName: 'JWT', mallHS: 'Mall', state: 'Rajasthan' },
  'KAL': { storeName: 'KAL', mallHS: 'High-Street', state: 'Haryana' },
  'KAM': { storeName: 'KAM', mallHS: 'High-Street', state: 'Haryana' },
  'KCM': { storeName: 'KCM', mallHS: 'High-Street', state: 'Kerala' },
  'KCP': { storeName: 'KCP', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'KCQ': { storeName: 'KCQ', mallHS: 'High-Street', state: 'Kerala' },
  'KCV': { storeName: 'KCV', mallHS: 'Mall', state: 'Kerala' },
  'KDV': { storeName: 'KDV', mallHS: 'Shop-N-Shop', state: 'Maharashtra' },
  'KGR': { storeName: 'KGR', mallHS: 'High-Street', state: 'Maharashtra' },
  'KHM': { storeName: 'KHM', mallHS: 'High-Street', state: 'Maharashtra' },
  'KIQ': { storeName: 'KIQ', mallHS: 'High-Street', state: 'Telangana' },
  'KKV': { storeName: 'KKV', mallHS: 'High-Street', state: 'Andhra Pradesh' },
  'KLH': { storeName: 'KLH', mallHS: 'High-Street', state: 'Maharashtra' },
  'KLM': { storeName: 'KLM', mallHS: 'Mall', state: 'Kerala' },
  'KLQ': { storeName: 'KLQ', mallHS: 'Mall', state: 'Kerala' },
  'KLU': { storeName: 'KLU', mallHS: 'Mall', state: 'Kerala' },
  'KLV': { storeName: 'KLV', mallHS: 'High-Street', state: 'Maharashtra' },
  'KLY': { storeName: 'KLY', mallHS: 'Mall', state: 'Maharashtra' },
  'KMQ': { storeName: 'KMQ', mallHS: 'High-Street', state: 'Kerala' },
  'KNM': { storeName: 'KNM', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'KNP': { storeName: 'KNP', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'KNQ': { storeName: 'KNQ', mallHS: 'High-Street', state: 'Kerala' },
  'KNR': { storeName: 'KNR', mallHS: 'High-Street', state: 'Kerala' },
  'KOB': { storeName: 'KOB', mallHS: 'Mall', state: 'Chhattisgarh' },
  'KOL': { storeName: 'KOL', mallHS: 'High-Street', state: 'Kerala' },
  'KOM': { storeName: 'KOM', mallHS: 'High-Street', state: 'Rajasthan' },
  'KOO': { storeName: 'KOO', mallHS: 'High-Street', state: 'Rajasthan' },
  'KOQ': { storeName: 'KOQ', mallHS: 'High-Street', state: 'Kerala' },
  'KOT': { storeName: 'KOT', mallHS: 'High-Street', state: 'Kerala' },
  'KPM': { storeName: 'KPM', mallHS: 'Mall', state: 'Maharashtra' },
  'KPQ': { storeName: 'KPQ', mallHS: 'Mall', state: 'Maharashtra' },
  'KPS': { storeName: 'KPS', mallHS: 'Mall', state: 'Maharashtra' },
  'KRM': { storeName: 'KRM', mallHS: 'High-Street', state: 'Telangana' },
  'KRQ': { storeName: 'KRQ', mallHS: 'High-Street', state: 'Maharashtra' },
  'KRV': { storeName: 'KRV', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'KSQ': { storeName: 'KSQ', mallHS: 'High-Street', state: 'Andhra Pradesh' },
  'KST': { storeName: 'KST', mallHS: 'High-Street', state: 'Kerala' },
  'KZQ': { storeName: 'KZQ', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'LAQ': { storeName: 'LAQ', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'LAS': { storeName: 'LAS', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'LAV': { storeName: 'LAV', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'LBV': { storeName: 'LBV', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'LCM': { storeName: 'LCM', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'LCQ': { storeName: 'LCQ', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'LDH': { storeName: 'LDH', mallHS: 'High-Street', state: 'Punjab' },
  'LDM': { storeName: 'LDM', mallHS: 'High-Street', state: 'Punjab' },
  'LGQ': { storeName: 'LGQ', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'LHM': { storeName: 'LHM', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'LHQ': { storeName: 'LHQ', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'LIM': { storeName: 'LIM', mallHS: 'Mall', state: 'Maharashtra' },
  'LKM': { storeName: 'LKM', mallHS: 'High-Street', state: 'Maharashtra' },
  'LKQ': { storeName: 'LKQ', mallHS: 'High-Street', state: 'Maharashtra' },
  'LKR': { storeName: 'LKR', mallHS: 'High-Street', state: 'Maharashtra' },
  'LLQ': { storeName: 'LLQ', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'LLU': { storeName: 'LLU', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'LMD': { storeName: 'LMD', mallHS: 'Mall', state: 'Punjab' },
  'LMM': { storeName: 'LMM', mallHS: 'High-Street', state: 'Punjab' },
  'LMQ': { storeName: 'LMQ', mallHS: 'Mall', state: 'Punjab' },
  'LMS': { storeName: 'LMS', mallHS: 'High-Street', state: 'Punjab' },
  'LOM': { storeName: 'LOM', mallHS: 'Mall', state: 'Punjab' },
  'LPM': { storeName: 'LPM', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'LPQ': { storeName: 'LPQ', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'LSQ': { storeName: 'LSQ', mallHS: 'Mall', state: 'Punjab' },
  'LTM': { storeName: 'LTM', mallHS: 'High-Street', state: 'Maharashtra' },
  'LTR': { storeName: 'LTR', mallHS: 'High-Street', state: 'Maharashtra' },
  'LUH': { storeName: 'LUH', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'LUM': { storeName: 'LUM', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'LUP': { storeName: 'LUP', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'MAQ': { storeName: 'MAQ', mallHS: 'Airport', state: 'Maharashtra' },
  'MAS': { storeName: 'MAS', mallHS: 'Airport', state: 'Maharashtra' },
  'MBQ': { storeName: 'MBQ', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'MCA': { storeName: 'MCA', mallHS: 'Mall', state: 'Maharashtra' },
  'MCP': { storeName: 'MCP', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'MCQ': { storeName: 'MCQ', mallHS: 'Mall', state: 'Tamil Nadu' },
  'MDM': { storeName: 'MDM', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'MDN': { storeName: 'MDN', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'MDQ': { storeName: 'MDQ', mallHS: 'Airport', state: 'Maharashtra' },
  'MDR': { storeName: 'MDR', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'MDT': { storeName: 'MDT', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'MDY': { storeName: 'MDY', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'MEQ': { storeName: 'MEQ', mallHS: 'Mall', state: 'Tamil Nadu' },
  'MEX': { storeName: 'MEX', mallHS: 'Mall', state: 'Tamil Nadu' },
  'MFM': { storeName: 'MFM', mallHS: 'Mall', state: 'Tamil Nadu' },
  'MFQ': { storeName: 'MFQ', mallHS: 'Mall', state: 'Tamil Nadu' },
  'MFS': { storeName: 'MFS', mallHS: 'Mall', state: 'Tamil Nadu' },
  'MFV': { storeName: 'MFV', mallHS: 'Mall', state: 'Tamil Nadu' },
  'MGQ': { storeName: 'MGQ', mallHS: 'Mall', state: 'Karnataka' },
  'MGS': { storeName: 'MGS', mallHS: 'Mall', state: 'Karnataka' },
  'MGV': { storeName: 'MGV', mallHS: 'Mall', state: 'Karnataka' },
  'MHM': { storeName: 'MHM', mallHS: 'High-Street', state: 'Punjab' },
  'MIQ': { storeName: 'MIQ', mallHS: 'Airport', state: 'Maharashtra' },
  'MJQ': { storeName: 'MJQ', mallHS: 'Mall', state: 'Maharashtra' },
  'MKM': { storeName: 'MKM', mallHS: 'Mall', state: 'Tamil Nadu' },
  'MKQ': { storeName: 'MKQ', mallHS: 'Mall', state: 'Tamil Nadu' },
  'MKS': { storeName: 'MKS', mallHS: 'Mall', state: 'Tamil Nadu' },
  'MLD': { storeName: 'MLD', mallHS: 'High-Street', state: 'Maharashtra' },
  'MMC': { storeName: 'MMC', mallHS: 'Mall', state: 'Tamil Nadu' },
  'MMM': { storeName: 'MMM', mallHS: 'Mall', state: 'Maharashtra' },
  'MMQ': { storeName: 'MMQ', mallHS: 'Mall', state: 'Tamil Nadu' },
  'MMV': { storeName: 'MMV', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'MNM': { storeName: 'MNM', mallHS: 'High-Street', state: 'Karnataka' },
  'MNQ': { storeName: 'MNQ', mallHS: 'High-Street', state: 'Karnataka' },
  'MOB': { storeName: 'MOB', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'MOM': { storeName: 'MOM', mallHS: 'Mall', state: 'Karnataka' },
  'MOQ': { storeName: 'MOQ', mallHS: 'Mall', state: 'Karnataka' },
  'MOS': { storeName: 'MOS', mallHS: 'Mall', state: 'Karnataka' },
  'MPM': { storeName: 'MPM', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'MRC': { storeName: 'MRC', mallHS: 'Mall', state: 'Karnataka' },
  'MRM': { storeName: 'MRM', mallHS: 'Mall', state: 'Karnataka' },
  'MRQ': { storeName: 'MRQ', mallHS: 'Mall', state: 'Karnataka' },
  'MRT': { storeName: 'MRT', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'MRV': { storeName: 'MRV', mallHS: 'High-Street', state: 'Karnataka' },
  'MSM': { storeName: 'MSM', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'MTM': { storeName: 'MTM', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'MUM': { storeName: 'MUM', mallHS: 'Mall', state: 'Tamil Nadu' },
  'MUS': { storeName: 'MUS', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'MVQ': { storeName: 'MVQ', mallHS: 'Mall', state: 'Tamil Nadu' },
  'MVR': { storeName: 'MVR', mallHS: 'Mall', state: 'Tamil Nadu' },
  'MVS': { storeName: 'MVS', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'MYQ': { storeName: 'MYQ', mallHS: 'High-Street', state: 'Karnataka' },
  'MYR': { storeName: 'MYR', mallHS: 'Mall', state: 'Karnataka' },
  'MZF': { storeName: 'MZF', mallHS: 'High-Street', state: 'Bihar' },
  'MZM': { storeName: 'MZM', mallHS: 'Mall', state: 'Bihar' },
  'NCL': { storeName: 'NCL', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'NCV': { storeName: 'NCV', mallHS: 'High-Street', state: 'Maharashtra' },
  'NDD': { storeName: 'NDD', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'NDQ': { storeName: 'NDQ', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'NDS': { storeName: 'NDS', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'NEM': { storeName: 'NEM', mallHS: 'Mall', state: 'Maharashtra' },
  'NES': { storeName: 'NES', mallHS: 'Mall', state: 'Maharashtra' },
  'NEV': { storeName: 'NEV', mallHS: 'Mall', state: 'Maharashtra' },
  'NGM': { storeName: 'NGM', mallHS: 'High-Street', state: 'Maharashtra' },
  'NGP': { storeName: 'NGP', mallHS: 'High-Street', state: 'Maharashtra' },
  'NGS': { storeName: 'NGS', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'NIM': { storeName: 'NIM', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'NIQ': { storeName: 'NIQ', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'NKM': { storeName: 'NKM', mallHS: 'Mall', state: 'Maharashtra' },
  'NKQ': { storeName: 'NKQ', mallHS: 'Mall', state: 'Maharashtra' },
  'NKS': { storeName: 'NKS', mallHS: 'Mall', state: 'Maharashtra' },
  'NKV': { storeName: 'NKV', mallHS: 'Mall', state: 'Maharashtra' },
  'NLR': { storeName: 'NLR', mallHS: 'High-Street', state: 'Andhra Pradesh' },
  'NND': { storeName: 'NND', mallHS: 'High-Street', state: 'Maharashtra' },
  'NNM': { storeName: 'NNM', mallHS: 'High-Street', state: 'Maharashtra' },
  'NPM': { storeName: 'NPM', mallHS: 'High-Street', state: 'Maharashtra' },
  'NPQ': { storeName: 'NPQ', mallHS: 'High-Street', state: 'Maharashtra' },
  'NSK': { storeName: 'NSK', mallHS: 'High-Street', state: 'Maharashtra' },
  'NSM': { storeName: 'NSM', mallHS: 'High-Street', state: 'Maharashtra' },
  'NSQ': { storeName: 'NSQ', mallHS: 'High-Street', state: 'Maharashtra' },
  'NSV': { storeName: 'NSV', mallHS: 'High-Street', state: 'Maharashtra' },
  'NTP': { storeName: 'NTP', mallHS: 'Mall', state: 'Maharashtra' },
  'NTQ': { storeName: 'NTQ', mallHS: 'Mall', state: 'Maharashtra' },
  'NVV': { storeName: 'NVV', mallHS: 'High-Street', state: 'Maharashtra' },
  'NZB': { storeName: 'NZB', mallHS: 'High-Street', state: 'Telangana' },
  'NZQ': { storeName: 'NZQ', mallHS: 'High-Street', state: 'Telangana' },
  'PAM': { storeName: 'PAM', mallHS: 'Mall', state: 'Maharashtra' },
  'PBM': { storeName: 'PBM', mallHS: 'High-Street', state: 'Bihar' },
  'PBQ': { storeName: 'PBQ', mallHS: 'High-Street', state: 'Bihar' },
  'PBS': { storeName: 'PBS', mallHS: 'High-Street', state: 'Bihar' },
  'PCM': { storeName: 'PCM', mallHS: 'High-Street', state: 'Punjab' },
  'PDC': { storeName: 'PDC', mallHS: 'High-Street', state: 'Puducherry' },
  'PDM': { storeName: 'PDM', mallHS: 'High-Street', state: 'Puducherry' },
  'PDQ': { storeName: 'PDQ', mallHS: 'High-Street', state: 'Puducherry' },
  'PEM': { storeName: 'PEM', mallHS: 'Mall', state: 'Maharashtra' },
  'PFQ': { storeName: 'PFQ', mallHS: 'High-Street', state: 'Bihar' },
  'PGQ': { storeName: 'PGQ', mallHS: 'High-Street', state: 'Maharashtra' },
  'PGV': { storeName: 'PGV', mallHS: 'High-Street', state: 'Maharashtra' },
  'PHQ': { storeName: 'PHQ', mallHS: 'Mall', state: 'Maharashtra' },
  'PHX': { storeName: 'PHX', mallHS: 'Mall', state: 'Maharashtra' },
  'PJM': { storeName: 'PJM', mallHS: 'Mall', state: 'Maharashtra' },
  'PJQ': { storeName: 'PJQ', mallHS: 'High-Street', state: 'Maharashtra' },
  'PKM': { storeName: 'PKM', mallHS: 'Mall', state: 'Maharashtra' },
  'PLM': { storeName: 'PLM', mallHS: 'Mall', state: 'Bihar' },
  'PLQ': { storeName: 'PLQ', mallHS: 'Mall', state: 'Bihar' },
  'PMG': { storeName: 'PMG', mallHS: 'High-Street', state: 'Maharashtra' },
  'PMM': { storeName: 'PMM', mallHS: 'Mall', state: 'Maharashtra' },
  'PMP': { storeName: 'PMP', mallHS: 'High-Street', state: 'Maharashtra' },
  'PMQ': { storeName: 'PMQ', mallHS: 'Mall', state: 'Maharashtra' },
  'PMS': { storeName: 'PMS', mallHS: 'Mall', state: 'Maharashtra' },
  'PNM': { storeName: 'PNM', mallHS: 'High-Street', state: 'Bihar' },
  'POT': { storeName: 'POT', mallHS: 'Mall', state: 'Punjab' },
  'PPM': { storeName: 'PPM', mallHS: 'Mall', state: 'Maharashtra' },
  'PRB': { storeName: 'PRB', mallHS: 'High-Street', state: 'Bihar' },
  'PSM': { storeName: 'PSM', mallHS: 'Mall', state: 'Maharashtra' },
  'PSS': { storeName: 'PSS', mallHS: 'Mall', state: 'Maharashtra' },
  'PTA': { storeName: 'PTA', mallHS: 'High-Street', state: 'Punjab' },
  'PTM': { storeName: 'PTM', mallHS: 'High-Street', state: 'Punjab' },
  'PTN': { storeName: 'PTN', mallHS: 'High-Street', state: 'Bihar' },
  'PTQ': { storeName: 'PTQ', mallHS: 'High-Street', state: 'Punjab' },
  'PUN': { storeName: 'PUN', mallHS: 'High-Street', state: 'Maharashtra' },
  'PWQ': { storeName: 'PWQ', mallHS: 'Mall', state: 'Maharashtra' },
  'RBM': { storeName: 'RBM', mallHS: 'Mall', state: 'Karnataka' },
  'RCM': { storeName: 'RCM', mallHS: 'Mall', state: 'Chhattisgarh' },
  'RCQ': { storeName: 'RCQ', mallHS: 'High-Street', state: 'Jharkhand' },
  'RCV': { storeName: 'RCV', mallHS: 'Mall', state: 'Gujarat' },
  'RHM': { storeName: 'RHM', mallHS: 'High-Street', state: 'Jharkhand' },
  'RIC': { storeName: 'RIC', mallHS: 'Mall', state: 'Chhattisgarh' },
  'RIM': { storeName: 'RIM', mallHS: 'Mall', state: 'Chhattisgarh' },
  'RIP': { storeName: 'RIP', mallHS: 'Mall', state: 'Chhattisgarh' },
  'RIQ': { storeName: 'RIQ', mallHS: 'Mall', state: 'Chhattisgarh' },
  'RJQ': { storeName: 'RJQ', mallHS: 'High-Street', state: 'Andhra Pradesh' },
  'RKT': { storeName: 'RKT', mallHS: 'High-Street', state: 'Gujarat' },
  'RMQ': { storeName: 'RMQ', mallHS: 'Mall', state: 'Chhattisgarh' },
  'RNC': { storeName: 'RNC', mallHS: 'High-Street', state: 'Jharkhand' },
  'RNM': { storeName: 'RNM', mallHS: 'Mall', state: 'Jharkhand' },
  'RNQ': { storeName: 'RNQ', mallHS: 'Mall', state: 'Jharkhand' },
  'RNS': { storeName: 'RNS', mallHS: 'Mall', state: 'Jharkhand' },
  'RTK': { storeName: 'RTK', mallHS: 'High-Street', state: 'Haryana' },
  'RTM': { storeName: 'RTM', mallHS: 'High-Street', state: 'Haryana' },
  'RTQ': { storeName: 'RTQ', mallHS: 'High-Street', state: 'Haryana' },
  'RUK': { storeName: 'RUK', mallHS: 'High-Street', state: 'Odisha' },
  'RUQ': { storeName: 'RUQ', mallHS: 'High-Street', state: 'Odisha' },
  'RWA': { storeName: 'RWA', mallHS: 'High-Street', state: 'Madhya Pradesh' },
  'RYM': { storeName: 'RYM', mallHS: 'High-Street', state: 'Gujarat' },
  'RYQ': { storeName: 'RYQ', mallHS: 'High-Street', state: 'Gujarat' },
  'SAC': { storeName: 'SAC', mallHS: 'Mall', state: 'West Bengal' },
  'SAL': { storeName: 'SAL', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'SAP': { storeName: 'SAP', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'SAQ': { storeName: 'SAQ', mallHS: 'Mall', state: 'West Bengal' },
  'SAV': { storeName: 'SAV', mallHS: 'Mall', state: 'Gujarat' },
  'SBP': { storeName: 'SBP', mallHS: 'High-Street', state: 'Odisha' },
  'SCM': { storeName: 'SCM', mallHS: 'Mall', state: 'Assam' },
  'SGM': { storeName: 'SGM', mallHS: 'Mall', state: 'West Bengal' },
  'SHL': { storeName: 'SHL', mallHS: 'High-Street', state: 'Meghalaya' },
  'SHV': { storeName: 'SHV', mallHS: 'Mall', state: 'Karnataka' },
  'SIL': { storeName: 'SIL', mallHS: 'Mall', state: 'West Bengal' },
  'SIM': { storeName: 'SIM', mallHS: 'High-Street', state: 'West Bengal' },
  'SIS': { storeName: 'SIS', mallHS: 'Mall', state: 'Assam' },
  'SLM': { storeName: 'SLM', mallHS: 'High-Street', state: 'Gujarat' },
  'SLQ': { storeName: 'SLQ', mallHS: 'High-Street', state: 'Gujarat' },
  'SMM': { storeName: 'SMM', mallHS: 'High-Street', state: 'Maharashtra' },
  'SNG': { storeName: 'SNG', mallHS: 'High-Street', state: 'Maharashtra' },
  'SNM': { storeName: 'SNM', mallHS: 'Mall', state: 'Maharashtra' },
  'SNQ': { storeName: 'SNQ', mallHS: 'Mall', state: 'Maharashtra' },
  'SOL': { storeName: 'SOL', mallHS: 'High-Street', state: 'Maharashtra' },
  'SOM': { storeName: 'SOM', mallHS: 'High-Street', state: 'Maharashtra' },
  'SON': { storeName: 'SON', mallHS: 'High-Street', state: 'Haryana' },
  'SOV': { storeName: 'SOV', mallHS: 'High-Street', state: 'Maharashtra' },
  'SPP': { storeName: 'SPP', mallHS: 'High-Street', state: 'Gujarat' },
  'SPQ': { storeName: 'SPQ', mallHS: 'High-Street', state: 'Gujarat' },
  'SRM': { storeName: 'SRM', mallHS: 'Mall', state: 'Gujarat' },
  'SRN': { storeName: 'SRN', mallHS: 'Mall', state: 'Jammu And Kashmir' },
  'SRQ': { storeName: 'SRQ', mallHS: 'Mall', state: 'Jammu And Kashmir' },
  'SRR': { storeName: 'SRR', mallHS: 'Mall', state: 'Gujarat' },
  'SRT': { storeName: 'SRT', mallHS: 'High-Street', state: 'Gujarat' },
  'STN': { storeName: 'STN', mallHS: 'High-Street', state: 'Madhya Pradesh' },
  'SVC': { storeName: 'SVC', mallHS: 'Mall', state: 'West Bengal' },
  'SVQ': { storeName: 'SVQ', mallHS: 'Mall', state: 'Gujarat' },
  'SWD': { storeName: 'SWD', mallHS: 'Mall', state: 'Maharashtra' },
  'SWM': { storeName: 'SWM', mallHS: 'High-Street', state: 'Gujarat' },
  'TCM': { storeName: 'TCM', mallHS: 'Mall', state: 'Kerala' },
  'TCS': { storeName: 'TCS', mallHS: 'Mall', state: 'Kerala' },
  'TCY': { storeName: 'TCY', mallHS: 'Mall', state: 'Kerala' },
  'TFS': { storeName: 'TFS', mallHS: 'High-Street', state: 'Kerala' },
  'THM': { storeName: 'THM', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'TIV': { storeName: 'TIV', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'TKM': { storeName: 'TKM', mallHS: 'Mall', state: 'Maharashtra' },
  'TKS': { storeName: 'TKS', mallHS: 'Mall', state: 'Maharashtra' },
  'TLM': { storeName: 'TLM', mallHS: 'Mall', state: 'Kerala' },
  'TLQ': { storeName: 'TLQ', mallHS: 'Mall', state: 'Kerala' },
  'TLU': { storeName: 'TLU', mallHS: 'Mall', state: 'Kerala' },
  'TMQ': { storeName: 'TMQ', mallHS: 'High-Street', state: 'Kerala' },
  'TNL': { storeName: 'TNL', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'TPM': { storeName: 'TPM', mallHS: 'High-Street', state: 'Kerala' },
  'TRC': { storeName: 'TRC', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'TSV': { storeName: 'TSV', mallHS: 'Mall', state: 'Karnataka' },
  'TTQ': { storeName: 'TTQ', mallHS: 'Mall', state: 'Kerala' },
  'TTS': { storeName: 'TTS', mallHS: 'Mall', state: 'Kerala' },
  'TTV': { storeName: 'TTV', mallHS: 'Mall', state: 'Kerala' },
  'TVL': { storeName: 'TVL', mallHS: 'High-Street', state: 'Kerala' },
  'TVM': { storeName: 'TVM', mallHS: 'Mall', state: 'Maharashtra' },
  'TVQ': { storeName: 'TVQ', mallHS: 'Mall', state: 'Maharashtra' },
  'TVS': { storeName: 'TVS', mallHS: 'Mall', state: 'Maharashtra' },
  'TZR': { storeName: 'TZR', mallHS: 'High-Street', state: 'Assam' },
  'UBM': { storeName: 'UBM', mallHS: 'Mall', state: 'Odisha' },
  'UBQ': { storeName: 'UBQ', mallHS: 'Mall', state: 'Odisha' },
  'UDQ': { storeName: 'UDQ', mallHS: 'Mall', state: 'Rajasthan' },
  'UDR': { storeName: 'UDR', mallHS: 'Mall', state: 'Rajasthan' },
  'ULS': { storeName: 'ULS', mallHS: 'Mall', state: 'Rajasthan' },
  'VAM': { storeName: 'VAM', mallHS: 'High-Street', state: 'Gujarat' },
  'VAP': { storeName: 'VAP', mallHS: 'High-Street', state: 'Gujarat' },
  'VBQ': { storeName: 'VBQ', mallHS: 'High-Street', state: 'Andhra Pradesh' },
  'VDS': { storeName: 'VDS', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'VIM': { storeName: 'VIM', mallHS: 'Mall', state: 'Maharashtra' },
  'VIQ': { storeName: 'VIQ', mallHS: 'Mall', state: 'Maharashtra' },
  'VJQ': { storeName: 'VJQ', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'VKM': { storeName: 'VKM', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'VLM': { storeName: 'VLM', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'VLQ': { storeName: 'VLQ', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'VLR': { storeName: 'VLR', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'VNM': { storeName: 'VNM', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'VNS': { storeName: 'VNS', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'VSQ': { storeName: 'VSQ', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'VVP': { storeName: 'VVP', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'VWD': { storeName: 'VWD', mallHS: 'High-Street', state: 'Andhra Pradesh' },
  'VWM': { storeName: 'VWM', mallHS: 'High-Street', state: 'Andhra Pradesh' },
  'VWP': { storeName: 'VWP', mallHS: 'Mall', state: 'Andhra Pradesh' },
  'VWQ': { storeName: 'VWQ', mallHS: 'High-Street', state: 'Andhra Pradesh' },
  'VZG': { storeName: 'VZG', mallHS: 'High-Street', state: 'Andhra Pradesh' },
  'VZM': { storeName: 'VZM', mallHS: 'High-Street', state: 'Andhra Pradesh' },
  'VZQ': { storeName: 'VZQ', mallHS: 'High-Street', state: 'Andhra Pradesh' },
  'WRM': { storeName: 'WRM', mallHS: 'High-Street', state: 'Telangana' },
  'YMM': { storeName: 'YMM', mallHS: 'High-Street', state: 'Haryana' },
  'YMN': { storeName: 'YMN', mallHS: 'High-Street', state: 'Haryana' },
  'ZCQ': { storeName: 'ZCQ', mallHS: 'Mall', state: 'Punjab' 
};
