@

const storeMapping = {
  'AAM': { storeName: 'AAM', mallHS: '', state: '' },
  'AAQ': { storeName: 'AAQ', mallHS: 'Mall', state: 'Gujarat' },
  'AAS': { storeName: 'AAS', mallHS: 'Mall', state: 'Gujarat' },
  'ABD': { storeName: 'ABD', mallHS: 'High-Street', state: 'Gujarat' },
  'ABM': { storeName: 'ABM', mallHS: '', state: '' },
  'ABP': { storeName: 'ABP', mallHS: 'High-Street', state: 'Gujarat' },
  'ABQ': { storeName: 'ABQ', mallHS: 'High-Street', state: 'Gujarat' },
  'ABR': { storeName: 'ABR', mallHS: 'High-Street', state: 'Gujarat' },
  'ABV': { storeName: 'ABV', mallHS: 'High-Street', state: 'Bihar' },
  'ACQ': { storeName: 'ACQ', mallHS: 'High-Street', state: 'Haryana' },
  'ADM': { storeName: 'ADM', mallHS: 'High-Street', state: 'Gujarat' },
  'ADQ': { storeName: 'ADQ', mallHS: 'High-Street', state: 'Gujarat' },
  'ADS': { storeName: 'ADS', mallHS: 'High-Street', state: 'Gujarat' },
  'AEM': { storeName: 'AEM', mallHS: '', state: '' },
  'AGL': { storeName: 'AGL', mallHS: 'High-Street', state: 'Odisha' },
  'AGM': { storeName: 'AGM', mallHS: 'High-Street', state: 'Punjab' },
  'AGQ': { storeName: 'AGQ', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'AGT': { storeName: 'AGT', mallHS: 'High-Street', state: 'Tripura' },
  'AGV': { storeName: 'AGV', mallHS: 'High-Street', state: 'Maharashtra' },
  'AHM': { storeName: 'AHM', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'AHT': { storeName: 'AHT', mallHS: '', state: '' },
  'AIM': { storeName: 'AIM', mallHS: '', state: '' },
  'AJM': { storeName: 'AJM', mallHS: 'High-Street', state: 'Rajasthan' },
  'AJQ': { storeName: 'AJQ', mallHS: '', state: '' },
  'AJR': { storeName: 'AJR', mallHS: 'High-Street', state: 'Rajasthan' },
  'AJS': { storeName: 'AJS', mallHS: 'High-Street', state: 'Rajasthan' },
  'AKQ': { storeName: 'AKQ', mallHS: '', state: '' },
  'ALA': { storeName: 'ALA', mallHS: 'High-Street', state: 'Haryana' },
  'ALH': { storeName: 'ALH', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'ALM': { storeName: 'ALM', mallHS: 'High-Street', state: 'Haryana' },
  'ALQ': { storeName: 'ALQ', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'ALR': { storeName: 'ALR', mallHS: 'High-Street', state: 'Rajasthan' },
  'ALV': { storeName: 'ALV', mallHS: 'High-Street', state: 'Rajasthan' },
  'AMM': { storeName: 'AMM', mallHS: '', state: '' },
  'AMN': { storeName: 'AMN', mallHS: 'High-Street', state: 'Gujarat' },
  'AMQ': { storeName: 'AMQ', mallHS: 'Mall', state: 'Punjab' },
  'AMR': { storeName: 'AMR', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'AMT': { storeName: 'AMT', mallHS: 'Mall', state: 'Gujarat' },
  'AND': { storeName: 'AND', mallHS: 'High-Street', state: 'Maharashtra' },
  'ANM': { storeName: 'ANM', mallHS: '', state: '' },
  'ANQ': { storeName: 'ANQ', mallHS: 'High-Street', state: 'Gujarat' },
  'ANV': { storeName: 'ANV', mallHS: 'High-Street', state: 'Maharashtra' },
  'AOQ': { storeName: 'AOQ', mallHS: 'High-Street', state: 'Gujarat' },
  'AOS': { storeName: 'AOS', mallHS: 'High-Street', state: 'Gujarat' },
  'AP9': { storeName: 'AP9', mallHS: '', state: '' },
  'APM': { storeName: 'APM', mallHS: '', state: '' },
  'APQ': { storeName: 'APQ', mallHS: 'Mall', state: 'Maharashtra' },
  'APS': { storeName: 'APS', mallHS: '', state: '' },
  'APV': { storeName: 'APV', mallHS: 'Mall', state: 'Maharashtra' },
  'ARA': { storeName: 'ARA', mallHS: 'Mall', state: 'Punjab' },
  'ARM': { storeName: 'ARM', mallHS: 'High-Street', state: 'Punjab' },
  'ARQ': { storeName: 'ARQ', mallHS: 'High-Street', state: 'Punjab' },
  'ARS': { storeName: 'ARS', mallHS: 'High-Street', state: 'Punjab' },
  'ASD': { storeName: 'ASD', mallHS: '', state: '' },
  'ASH': { storeName: 'ASH', mallHS: '', state: '' },
  'ASM': { storeName: 'ASM', mallHS: '', state: '' },
  'ASN': { storeName: 'ASN', mallHS: 'High-Street', state: 'West Bengal' },
  'ASP': { storeName: 'ASP', mallHS: '', state: '' },
  'ASQ': { storeName: 'ASQ', mallHS: '', state: '' },
  'AST': { storeName: 'AST', mallHS: 'High-Street', state: 'Gujarat' },
  'ATM': { storeName: 'ATM', mallHS: 'Mall', state: 'Punjab' },
  'ATS': { storeName: 'ATS', mallHS: 'Mall', state: 'Punjab' },
  'AUJ': { storeName: 'AUJ', mallHS: '', state: '' },
  'AUM': { storeName: 'AUM', mallHS: 'Mall', state: 'Maharashtra' },
  'AUP': { storeName: 'AUP', mallHS: 'Mall', state: 'Maharashtra' },
  'AUQ': { storeName: 'AUQ', mallHS: 'High-Street', state: 'Maharashtra' },
  'AUS': { storeName: 'AUS', mallHS: 'High-Street', state: 'Maharashtra' },
  'AUV': { storeName: 'AUV', mallHS: 'High-Street', state: 'Maharashtra' },
  'AVS': { storeName: 'AVS', mallHS: '', state: '' },
  'AVT': { storeName: 'AVT', mallHS: 'High-Street', state: 'Maharashtra' },
  'AWM': { storeName: 'AWM', mallHS: 'High-Street', state: 'Rajasthan' },
  'AZV': { storeName: 'AZV', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'B1M': { storeName: 'B1M', mallHS: '', state: '' },
  'B2M': { storeName: 'B2M', mallHS: '', state: '' },
  'B2Q': { storeName: 'B2Q', mallHS: 'Mall', state: 'Chhattisgarh' },
  'B3M': { storeName: 'B3M', mallHS: '', state: '' },
  'B3Q': { storeName: 'B3Q', mallHS: 'Mall', state: 'Karnataka' },
  'B4M': { storeName: 'B4M', mallHS: '', state: '' },
  'B4Q': { storeName: 'B4Q', mallHS: '', state: '' },
  'B5Q': { storeName: 'B5Q', mallHS: '', state: '' },
  'B6M': { storeName: 'B6M', mallHS: '', state: '' },
  'B6Q': { storeName: 'B6Q', mallHS: '', state: '' },
  'B7M': { storeName: 'B7M', mallHS: '', state: '' },
  'B9M': { storeName: 'B9M', mallHS: '', state: '' },
  'BAL': { storeName: 'BAL', mallHS: '', state: '' },
  'BAQ': { storeName: 'BAQ', mallHS: 'High-Street', state: 'Odisha' },
  'BAV': { storeName: 'BAV', mallHS: 'Mall', state: 'Madhya Pradesh' },
  'BBM': { storeName: 'BBM', mallHS: 'Mall', state: 'Gujarat' },
  'BBO': { storeName: 'BBO', mallHS: '', state: '' },
  'BBQ': { storeName: 'BBQ', mallHS: 'Mall', state: 'Gujarat' },
  'BBR': { storeName: 'BBR', mallHS: 'Mall', state: 'Odisha' },
  'BCA': { storeName: 'BCA', mallHS: '', state: '' },
  'BCC': { storeName: 'BCC', mallHS: 'Mall', state: 'Karnataka' },
  'BCM': { storeName: 'BCM', mallHS: 'High-Street', state: 'Chhattisgarh' },
  'BCQ': { storeName: 'BCQ', mallHS: 'Mall', state: 'Karnataka' },
  'BCV': { storeName: 'BCV', mallHS: 'Mall', state: 'Gujarat' },
  'BDD': { storeName: 'BDD', mallHS: '', state: '' },
  'BDL': { storeName: 'BDL', mallHS: '', state: '' },
  'BDQ': { storeName: 'BDQ', mallHS: '', state: '' },
  'BDR': { storeName: 'BDR', mallHS: 'High-Street', state: 'Karnataka' },
  'BF2': { storeName: 'BF2', mallHS: '', state: '' },
  'BF9': { storeName: 'BF9', mallHS: '', state: '' },
  'BFF': { storeName: 'BFF', mallHS: '', state: '' },
  'BFM': { storeName: 'BFM', mallHS: 'Mall', state: 'Karnataka' },
  'BFQ': { storeName: 'BFQ', mallHS: 'Mall', state: 'Karnataka' },
  'BFS': { storeName: 'BFS', mallHS: 'Mall', state: 'Karnataka' },
  'BG4': { storeName: 'BG4', mallHS: '', state: '' },
  'BGB': { storeName: 'BGB', mallHS: 'High-Street', state: 'Karnataka' },
  'BGH': { storeName: 'BGH', mallHS: '', state: '' },
  'BGL': { storeName: 'BGL', mallHS: 'High-Street', state: 'Karnataka' },
  'BGM': { storeName: 'BGM', mallHS: 'High-Street', state: 'Karnataka' },
  'BGN': { storeName: 'BGN', mallHS: '', state: '' },
  'BGQ': { storeName: 'BGQ', mallHS: 'High-Street', state: 'Karnataka' },
  'BGV': { storeName: 'BGV', mallHS: '', state: '' },
  'BHJ': { storeName: 'BHJ', mallHS: 'High-Street', state: 'Gujarat' },
  'BHL': { storeName: 'BHL', mallHS: 'Mall', state: 'Chhattisgarh' },
  'BHR': { storeName: 'BHR', mallHS: 'High-Street', state: 'Karnataka' },
  'BHU': { storeName: 'BHU', mallHS: 'High-Street', state: 'Odisha' },
  'BIN': { storeName: 'BIN', mallHS: 'High-Street', state: 'Karnataka' },
  'BIQ': { storeName: 'BIQ', mallHS: 'High-Street', state: 'Karnataka' },
  'BIV': { storeName: 'BIV', mallHS: 'High-Street', state: 'Karnataka' },
  'BJM': { storeName: 'BJM', mallHS: 'High-Street', state: 'Karnataka' },
  'BJP': { storeName: 'BJP', mallHS: '', state: '' },
  'BJQ': { storeName: 'BJQ', mallHS: 'High-Street', state: 'Karnataka' },
  'BJV': { storeName: 'BJV', mallHS: 'Mall', state: 'Karnataka' },
  'BJY': { storeName: 'BJY', mallHS: 'High-Street', state: 'Karnataka' },
  'BKM': { storeName: 'BKM', mallHS: 'Mall', state: 'Karnataka' },
  'BKQ': { storeName: 'BKQ', mallHS: 'High-Street', state: 'Karnataka' },
  'BKR': { storeName: 'BKR', mallHS: 'High-Street', state: 'Rajasthan' },
  'BLG': { storeName: 'BLG', mallHS: 'High-Street', state: 'Karnataka' },
  'BLL': { storeName: 'BLL', mallHS: 'High-Street', state: 'Karnataka' },
  'BLM': { storeName: 'BLM', mallHS: 'High-Street', state: 'Karnataka' },
  'BLP': { storeName: 'BLP', mallHS: 'High-Street', state: 'Maharashtra' },
  'BLQ': { storeName: 'BLQ', mallHS: 'Mall', state: 'Karnataka' },
  'BLU': { storeName: 'BLU', mallHS: 'Mall', state: 'Karnataka' },
  'BLV': { storeName: 'BLV', mallHS: 'High-Street', state: 'Karnataka' },
  'BLW': { storeName: 'BLW', mallHS: '', state: '' },
  'BM8': { storeName: 'BM8', mallHS: '', state: '' },
  'BM9': { storeName: 'BM9', mallHS: '', state: '' },
  'BMA': { storeName: 'BMA', mallHS: '', state: '' },
  'BME': { storeName: 'BME', mallHS: '', state: '' },
  'BMM': { storeName: 'BMM', mallHS: 'Mall', state: 'Karnataka' },
  'BMP': { storeName: 'BMP', mallHS: '', state: '' },
  'BMS': { storeName: 'BMS', mallHS: 'Mall', state: 'Karnataka' },
  'BMV': { storeName: 'BMV', mallHS: '', state: '' },
  'BNL': { storeName: 'BNL', mallHS: 'High-Street', state: 'Punjab' },
  'BNM': { storeName: 'BNM', mallHS: 'High-Street', state: 'Punjab' },
  'BNQ': { storeName: 'BNQ', mallHS: 'High-Street', state: 'Punjab' },
  'BNR': { storeName: 'BNR', mallHS: 'High-Street', state: 'Gujarat' },
  'BO2': { storeName: 'BO2', mallHS: '', state: '' },
  'BOM': { storeName: 'BOM', mallHS: 'Mall', state: 'Karnataka' },
  'BOR': { storeName: 'BOR', mallHS: '', state: '' },
  'BOU': { storeName: 'BOU', mallHS: '', state: '' },
  'BOV': { storeName: 'BOV', mallHS: '', state: '' },
  'BPL': { storeName: 'BPL', mallHS: 'High-Street', state: 'Madhya Pradesh' },
  'BPM': { storeName: 'BPM', mallHS: 'Mall', state: 'Madhya Pradesh' },
  'BPQ': { storeName: 'BPQ', mallHS: 'Mall', state: 'Madhya Pradesh' },
  'BPR': { storeName: 'BPR', mallHS: 'High-Street', state: 'Madhya Pradesh' },
  'BPS': { storeName: 'BPS', mallHS: 'Mall', state: 'Madhya Pradesh' },
  'BPV': { storeName: 'BPV', mallHS: '', state: '' },
  'BQM': { storeName: 'BQM', mallHS: 'High-Street', state: 'Karnataka' },
  'BQQ': { storeName: 'BQQ', mallHS: 'High-Street', state: 'Karnataka' },
  'BRD': { storeName: 'BRD', mallHS: 'High-Street', state: 'Gujarat' },
  'BRH': { storeName: 'BRH', mallHS: 'High-Street', state: 'Gujarat' },
  'BRM': { storeName: 'BRM', mallHS: 'High-Street', state: 'Gujarat' },
  'BRP': { storeName: 'BRP', mallHS: '', state: '' },
  'BRQ': { storeName: 'BRQ', mallHS: 'High-Street', state: 'Gujarat' },
  'BRS': { storeName: 'BRS', mallHS: 'High-Street', state: 'Gujarat' },
  'BRT': { storeName: 'BRT', mallHS: '', state: '' },
  'BRV': { storeName: 'BRV', mallHS: 'High-Street', state: 'Gujarat' },
  'BRZ': { storeName: 'BRZ', mallHS: 'Mall', state: 'Karnataka' },
  'BSM': { storeName: 'BSM', mallHS: 'Mall', state: 'Karnataka' },
  'BSP': { storeName: 'BSP', mallHS: 'Mall', state: 'Chhattisgarh' },
  'BSQ': { storeName: 'BSQ', mallHS: 'High-Street', state: 'Karnataka' },
  'BSS': { storeName: 'BSS', mallHS: 'High-Street', state: 'Karnataka' },
  'BST': { storeName: 'BST', mallHS: 'Shop-N-Shop', state: 'Karnataka' },
  'BTD': { storeName: 'BTD', mallHS: 'High-Street', state: 'Punjab' },
  'BTM': { storeName: 'BTM', mallHS: 'High-Street', state: 'Punjab' },
  'BUM': { storeName: 'BUM', mallHS: '', state: '' },
  'BUQ': { storeName: 'BUQ', mallHS: '', state: '' },
  'BV4': { storeName: 'BV4', mallHS: '', state: '' },
  'BVC': { storeName: 'BVC', mallHS: 'Mall', state: 'Karnataka' },
  'BVL': { storeName: 'BVL', mallHS: '', state: '' },
  'BVM': { storeName: 'BVM', mallHS: 'High-Street', state: 'Madhya Pradesh' },
  'BVQ': { storeName: 'BVQ', mallHS: 'Mall', state: 'Karnataka' },
  'BVS': { storeName: 'BVS', mallHS: 'Mall', state: 'Karnataka' },
  'BVY': { storeName: 'BVY', mallHS: '', state: '' },
  'BWM': { storeName: 'BWM', mallHS: 'High-Street', state: 'Odisha' },
  'BWQ': { storeName: 'BWQ', mallHS: 'High-Street', state: 'Karnataka' },
  'BXM': { storeName: 'BXM', mallHS: 'High-Street', state: 'Odisha' },
  'BXQ': { storeName: 'BXQ', mallHS: 'High-Street', state: 'Odisha' },
  'BYM': { storeName: 'BYM', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'BYQ': { storeName: 'BYQ', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'BYS': { storeName: 'BYS', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'BZM': { storeName: 'BZM', mallHS: 'High-Street', state: 'Karnataka' },
  'BZQ': { storeName: 'BZQ', mallHS: 'Mall', state: 'Karnataka' },
  'CAM': { storeName: 'CAM', mallHS: 'Mall', state: 'West Bengal' },
  'CAP': { storeName: 'CAP', mallHS: 'Mall', state: 'West Bengal' },
  'CAQ': { storeName: 'CAQ', mallHS: 'Mall', state: 'West Bengal' },
  'CAV': { storeName: 'CAV', mallHS: 'Mall', state: 'West Bengal' },
  'CBM': { storeName: 'CBM', mallHS: 'High-Street', state: 'Maharashtra' },
  'CBQ': { storeName: 'CBQ', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'CCK': { storeName: 'CCK', mallHS: 'Mall', state: 'West Bengal' },
  'CCM': { storeName: 'CCM', mallHS: 'Mall', state: 'West Bengal' },
  'CCQ': { storeName: 'CCQ', mallHS: 'Mall', state: 'West Bengal' },
  'CCR': { storeName: 'CCR', mallHS: 'Mall', state: 'West Bengal' },
  'CCU': { storeName: 'CCU', mallHS: 'High-Street', state: 'West Bengal' },
  'CDM': { storeName: 'CDM', mallHS: 'High-Street', state: 'Chandigarh' },
  'CDQ': { storeName: 'CDQ', mallHS: 'High-Street', state: 'Chandigarh' },
  'CEM': { storeName: 'CEM', mallHS: '', state: '' },
  'CF9': { storeName: 'CF9', mallHS: '', state: '' },
  'CFM': { storeName: 'CFM', mallHS: 'Mall', state: 'Tamil Nadu' },
  'CFQ': { storeName: 'CFQ', mallHS: 'Mall', state: 'Tamil Nadu' },
  'CGM': { storeName: 'CGM', mallHS: 'Mall', state: 'Kerala' },
  'CGQ': { storeName: 'CGQ', mallHS: 'Mall', state: 'Kerala' },
  'CGR': { storeName: 'CGR', mallHS: '', state: '' },
  'CGV': { storeName: 'CGV', mallHS: 'Mall', state: 'Kerala' },
  'CH2': { storeName: 'CH2', mallHS: '', state: '' },
  'CHM': { storeName: 'CHM', mallHS: 'Mall', state: 'Kerala' },
  'CHQ': { storeName: 'CHQ', mallHS: 'Mall', state: 'Chandigarh' },
  'CHS': { storeName: 'CHS', mallHS: 'Mall', state: 'Chandigarh' },
  'CHW': { storeName: 'CHW', mallHS: 'High-Street', state: 'Madhya Pradesh' },
  'CIL': { storeName: 'CIL', mallHS: 'High-Street', state: 'Kerala' },
  'CIQ': { storeName: 'CIQ', mallHS: 'Mall', state: 'Kerala' },
  'CIS': { storeName: 'CIS', mallHS: 'Mall', state: 'Kerala' },
  'CKM': { storeName: 'CKM', mallHS: '', state: '' },
  'CKP': { storeName: 'CKP', mallHS: 'High-Street', state: 'West Bengal' },
  'CKQ': { storeName: 'CKQ', mallHS: '', state: '' },
  'CKV': { storeName: 'CKV', mallHS: '', state: '' },
  'CLB': { storeName: 'CLB', mallHS: 'High-Street', state: 'Maharashtra' },
  'CLM': { storeName: 'CLM', mallHS: 'High-Street', state: 'West Bengal' },
  'CLQ': { storeName: 'CLQ', mallHS: 'Mall', state: 'West Bengal' },
  'CLU': { storeName: 'CLU', mallHS: '', state: '' },
  'CMM': { storeName: 'CMM', mallHS: 'Mall', state: 'West Bengal' },
  'CMQ': { storeName: 'CMQ', mallHS: 'Mall', state: 'West Bengal' },
  'CMS': { storeName: 'CMS', mallHS: 'Mall', state: 'West Bengal' },
  'CMV': { storeName: 'CMV', mallHS: 'High-Street', state: 'Maharashtra' },
  'CNB': { storeName: 'CNB', mallHS: 'Mall', state: 'West Bengal' },
  'COM': { storeName: 'COM', mallHS: 'Mall', state: 'Chandigarh' },
  'COQ': { storeName: 'COQ', mallHS: 'Mall', state: 'West Bengal' },
  'CPM': { storeName: 'CPM', mallHS: 'Mall', state: 'Tamil Nadu' },
  'CPQ': { storeName: 'CPQ', mallHS: 'Mall', state: 'Tamil Nadu' },
  'CPS': { storeName: 'CPS', mallHS: 'Mall', state: 'Tamil Nadu' },
  'CRB': { storeName: 'CRB', mallHS: 'Mall', state: 'West Bengal' },
  'CRQ': { storeName: 'CRQ', mallHS: '', state: '' },
  'CSC': { storeName: 'CSC', mallHS: 'Mall', state: 'West Bengal' },
  'CSD': { storeName: 'CSD', mallHS: 'High-Street', state: 'Chandigarh' },
  'CSM': { storeName: 'CSM', mallHS: 'Mall', state: 'West Bengal' },
  'CTK': { storeName: 'CTK', mallHS: 'High-Street', state: 'Odisha' },
  'CTM': { storeName: 'CTM', mallHS: 'High-Street', state: 'Kerala' },
  'CTQ': { storeName: 'CTQ', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'CTR': { storeName: 'CTR', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'CTT': { storeName: 'CTT', mallHS: '', state: '' },
  'CUQ': { storeName: 'CUQ', mallHS: '', state: '' },
  'CWM': { storeName: 'CWM', mallHS: '', state: '' },
  'CWT': { storeName: 'CWT', mallHS: 'High-Street', state: 'Maharashtra' },
  'DAL': { storeName: 'DAL', mallHS: 'Airport', state: 'Delhi' },
  'DAM': { storeName: 'DAM', mallHS: 'Mall', state: 'Delhi' },
  'DBR': { storeName: 'DBR', mallHS: 'High-Street', state: 'Assam' },
  'DCB': { storeName: 'DCB', mallHS: 'Mall', state: 'Jharkhand' },
  'DCM': { storeName: 'DCM', mallHS: 'Mall', state: 'Jharkhand' },
  'DCP': { storeName: 'DCP', mallHS: '', state: '' },
  'DDM': { storeName: 'DDM', mallHS: 'High-Street', state: 'Uttarakhand' },
  'DDO': { storeName: 'DDO', mallHS: 'High-Street', state: 'Uttarakhand' },
  'DDP': { storeName: 'DDP', mallHS: '', state: '' },
  'DDQ': { storeName: 'DDQ', mallHS: 'Mall', state: 'Uttarakhand' },
  'DDR': { storeName: 'DDR', mallHS: 'High-Street', state: 'Maharashtra' },
  'DDU': { storeName: 'DDU', mallHS: 'Mall', state: 'Uttarakhand' },
  'DDV': { storeName: 'DDV', mallHS: '', state: '' },
  'DEM': { storeName: 'DEM', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'DEQ': { storeName: 'DEQ', mallHS: 'Mall', state: 'Delhi' },
  'DGK': { storeName: 'DGK', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'DGM': { storeName: 'DGM', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'DGZ': { storeName: 'DGZ', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'DHB': { storeName: 'DHB', mallHS: '', state: '' },
  'DIM': { storeName: 'DIM', mallHS: '', state: '' },
  'DJM': { storeName: 'DJM', mallHS: '', state: '' },
  'DJQ': { storeName: 'DJQ', mallHS: 'High-Street', state: 'Delhi' },
  'DKM': { storeName: 'DKM', mallHS: 'Mall', state: 'Delhi' },
  'DKN': { storeName: 'DKN', mallHS: 'High-Street', state: 'Delhi' },
  'DLK': { storeName: 'DLK', mallHS: 'High-Street', state: 'Delhi' },
  'DLN': { storeName: 'DLN', mallHS: 'Mall', state: 'Delhi' },
  'DLQ': { storeName: 'DLQ', mallHS: 'High-Street', state: 'Delhi' },
  'DMP': { storeName: 'DMP', mallHS: 'High-Street', state: 'Nagaland' },
  'DNL': { storeName: 'DNL', mallHS: '', state: '' },
  'DNQ': { storeName: 'DNQ', mallHS: 'High-Street', state: 'Uttarakhand' },
  'DPE': { storeName: 'DPE', mallHS: 'Mall', state: 'Maharashtra' },
  'DPQ': { storeName: 'DPQ', mallHS: 'Mall', state: 'Delhi' },
  'DPS': { storeName: 'DPS', mallHS: 'Mall', state: 'Delhi' },
  'DRM': { storeName: 'DRM', mallHS: 'Mall', state: 'Delhi' },
  'DRP': { storeName: 'DRP', mallHS: 'Mall', state: 'Delhi' },
  'DRQ': { storeName: 'DRQ', mallHS: 'High-Street', state: 'Delhi' },
  'DRS': { storeName: 'DRS', mallHS: 'Mall', state: 'Delhi' },
  'DS4': { storeName: 'DS4', mallHS: '', state: '' },
  'DSM': { storeName: 'DSM', mallHS: 'High-Street', state: 'Delhi' },
  'DSQ': { storeName: 'DSQ', mallHS: 'Mall', state: 'Delhi' },
  'DTM': { storeName: 'DTM', mallHS: 'High-Street', state: 'Maharashtra' },
  'DUM': { storeName: 'DUM', mallHS: '', state: '' },
  'DUQ': { storeName: 'DUQ', mallHS: 'Mall', state: 'Uttarakhand' },
  'DVQ': { storeName: 'DVQ', mallHS: 'Mall', state: 'Delhi' },
  'DWM': { storeName: 'DWM', mallHS: 'Mall', state: 'Delhi' },
  'DWQ': { storeName: 'DWQ', mallHS: 'Mall', state: 'Delhi' },
  'DWS': { storeName: 'DWS', mallHS: '', state: '' },
  'DXL': { storeName: 'DXL', mallHS: 'High-Street', state: 'Delhi' },
  'DZM': { storeName: 'DZM', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'DZP': { storeName: 'DZP', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'DZQ': { storeName: 'DZQ', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'DZS': { storeName: 'DZS', mallHS: '', state: '' },
  'EBQ': { storeName: 'EBQ', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'ERD': { storeName: 'ERD', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'ERM': { storeName: 'ERM', mallHS: '', state: '' },
  'FBM': { storeName: 'FBM', mallHS: '', state: '' },
  'FCL': { storeName: 'FCL', mallHS: 'Mall', state: 'West Bengal' },
  'FCQ': { storeName: 'FCQ', mallHS: 'Mall', state: 'West Bengal' },
  'FDM': { storeName: 'FDM', mallHS: '', state: '' },
  'FGM': { storeName: 'FGM', mallHS: 'Mall', state: 'Karnataka' },
  'FMP': { storeName: 'FMP', mallHS: '', state: '' },
  'FMQ': { storeName: 'FMQ', mallHS: 'Mall', state: 'Karnataka' },
  'FMS': { storeName: 'FMS', mallHS: 'Mall', state: 'Karnataka' },
  'FPM': { storeName: 'FPM', mallHS: '', state: '' },
  'FPQ': { storeName: 'FPQ', mallHS: '', state: '' },
  'FPS': { storeName: 'FPS', mallHS: '', state: '' },
  'FRM': { storeName: 'FRM', mallHS: '', state: '' },
  'FSM': { storeName: 'FSM', mallHS: 'Mall', state: 'Karnataka' },
  'FSQ': { storeName: 'FSQ', mallHS: 'Mall', state: 'Karnataka' },
  'FSS': { storeName: 'FSS', mallHS: 'Mall', state: 'Karnataka' },
  'FX9': { storeName: 'FX9', mallHS: 'Mall', state: 'Tamil Nadu' },
  'G1Q': { storeName: 'G1Q', mallHS: '', state: '' },
  'GAS': { storeName: 'GAS', mallHS: 'Mall', state: 'Haryana' },
  'GBQ': { storeName: 'GBQ', mallHS: 'Mall', state: 'Sikkim' },
  'GCM': { storeName: 'GCM', mallHS: 'Mall', state: 'Assam' },
  'GDB': { storeName: 'GDB', mallHS: 'Mall', state: 'Madhya Pradesh' },
  'GDM': { storeName: 'GDM', mallHS: 'Mall', state: 'Haryana' },
  'GDQ': { storeName: 'GDQ', mallHS: 'Mall', state: 'Haryana' },
  'GGM': { storeName: 'GGM', mallHS: 'High-Street', state: 'Rajasthan' },
  'GGN': { storeName: 'GGN', mallHS: 'High-Street', state: 'Rajasthan' },
  'GGQ': { storeName: 'GGQ', mallHS: 'High-Street', state: 'Rajasthan' },
  'GGS': { storeName: 'GGS', mallHS: '', state: '' },
  'GGV': { storeName: 'GGV', mallHS: 'High-Street', state: 'Rajasthan' },
  'GHD': { storeName: 'GHD', mallHS: 'High-Street', state: 'Gujarat' },
  'GHM': { storeName: 'GHM', mallHS: 'High-Street', state: 'Gujarat' },
  'GHN': { storeName: 'GHN', mallHS: '', state: '' },
  'GIQ': { storeName: 'GIQ', mallHS: 'High-Street', state: 'Gujarat' },
  'GKM': { storeName: 'GKM', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'GKP': { storeName: 'GKP', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'GKQ': { storeName: 'GKQ', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'GKV': { storeName: 'GKV', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'GLM': { storeName: 'GLM', mallHS: 'Mall', state: 'Karnataka' },
  'GLQ': { storeName: 'GLQ', mallHS: 'Mall', state: 'Karnataka' },
  'GMM': { storeName: 'GMM', mallHS: 'Mall', state: 'Haryana' },
  'GMQ': { storeName: 'GMQ', mallHS: 'High-Street', state: 'Goa' },
  'GMS': { storeName: 'GMS', mallHS: 'Mall', state: 'Haryana' },
  'GNM': { storeName: 'GNM', mallHS: 'High-Street', state: 'Andhra Pradesh' },
  'GNQ': { storeName: 'GNQ', mallHS: 'High-Street', state: 'Andhra Pradesh' },
  'GNR': { storeName: 'GNR', mallHS: '', state: '' },
  'GNT': { storeName: 'GNT', mallHS: 'High-Street', state: 'Sikkim' },
  'GOA': { storeName: 'GOA', mallHS: 'High-Street', state: 'Goa' },
  'GOB': { storeName: 'GOB', mallHS: '', state: '' },
  'GOM': { storeName: 'GOM', mallHS: 'High-Street', state: 'Goa' },
  'GOP': { storeName: 'GOP', mallHS: '', state: '' },
  'GOQ': { storeName: 'GOQ', mallHS: 'High-Street', state: 'Goa' },
  'GOR': { storeName: 'GOR', mallHS: 'Mall', state: 'Maharashtra' },
  'GPM': { storeName: 'GPM', mallHS: '', state: '' },
  'GRD': { storeName: 'GRD', mallHS: 'High-Street', state: 'Maharashtra' },
  'GRM': { storeName: 'GRM', mallHS: 'High-Street', state: 'Maharashtra' },
  'GRQ': { storeName: 'GRQ', mallHS: 'Mall', state: 'Haryana' },
  'GSQ': { storeName: 'GSQ', mallHS: '', state: '' },
  'GTK': { storeName: 'GTK', mallHS: 'High-Street', state: 'Maharashtra' },
  'GTM': { storeName: 'GTM', mallHS: 'Mall', state: 'Maharashtra' },
  'GTQ': { storeName: 'GTQ', mallHS: 'Mall', state: 'Maharashtra' },
  'GTR': { storeName: 'GTR', mallHS: 'High-Street', state: 'Andhra Pradesh' },
  'GTS': { storeName: 'GTS', mallHS: 'Mall', state: 'Maharashtra' },
  'GUC': { storeName: 'GUC', mallHS: '', state: '' },
  'GUH': { storeName: 'GUH', mallHS: 'High-Street', state: 'Assam' },
  'GUL': { storeName: 'GUL', mallHS: 'High-Street', state: 'Karnataka' },
  'GUM': { storeName: 'GUM', mallHS: 'High-Street', state: 'Assam' },
  'GUN': { storeName: 'GUN', mallHS: 'Mall', state: 'Assam' },
  'GUQ': { storeName: 'GUQ', mallHS: 'High-Street', state: 'Assam' },
  'GUV': { storeName: 'GUV', mallHS: 'High-Street', state: 'Karnataka' },
  'GUZ': { storeName: 'GUZ', mallHS: 'High-Street', state: 'Assam' },
  'GVM': { storeName: 'GVM', mallHS: 'Mall', state: 'Sikkim' },
  'GVQ': { storeName: 'GVQ', mallHS: 'Mall', state: 'Goa' },
  'GWM': { storeName: 'GWM', mallHS: 'Mall', state: 'Madhya Pradesh' },
  'GWR': { storeName: 'GWR', mallHS: 'High-Street', state: 'Madhya Pradesh' },
  'GWV': { storeName: 'GWV', mallHS: 'High-Street', state: 'Andhra Pradesh' },
  'GYA': { storeName: 'GYA', mallHS: '', state: '' },
  'GYM': { storeName: 'GYM', mallHS: '', state: '' },
  'GZM': { storeName: 'GZM', mallHS: '', state: '' },
  'GZQ': { storeName: 'GZQ', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'H1M': { storeName: 'H1M', mallHS: '', state: '' },
  'H3M': { storeName: 'H3M', mallHS: '', state: '' },
  'H4M': { storeName: 'H4M', mallHS: '', state: '' },
  'H5M': { storeName: 'H5M', mallHS: '', state: '' },
  'HAM': { storeName: 'HAM', mallHS: 'Airport', state: 'Telangana' },
  'HAQ': { storeName: 'HAQ', mallHS: 'Airport', state: 'Telangana' },
  'HAV': { storeName: 'HAV', mallHS: 'High-Street', state: 'Telangana' },
  'HB9': { storeName: 'HB9', mallHS: '', state: '' },
  'HBQ': { storeName: 'HBQ', mallHS: 'High-Street', state: 'Telangana' },
  'HBS': { storeName: 'HBS', mallHS: 'High-Street', state: 'Telangana' },
  'HBU': { storeName: 'HBU', mallHS: 'Mall', state: 'Karnataka' },
  'HC2': { storeName: 'HC2', mallHS: '', state: '' },
  'HCM': { storeName: 'HCM', mallHS: 'Mall', state: 'Telangana' },
  'HCQ': { storeName: 'HCQ', mallHS: 'Mall', state: 'Telangana' },
  'HCS': { storeName: 'HCS', mallHS: 'Mall', state: 'Telangana' },
  'HCV': { storeName: 'HCV', mallHS: 'High-Street', state: 'Telangana' },
  'HDM': { storeName: 'HDM', mallHS: 'High-Street', state: 'Telangana' },
  'HDQ': { storeName: 'HDQ', mallHS: 'Mall', state: 'Telangana' },
  'HDR': { storeName: 'HDR', mallHS: 'High-Street', state: 'Uttarakhand' },
  'HDS': { storeName: 'HDS', mallHS: 'Mall', state: 'Telangana' },
  'HDV': { storeName: 'HDV', mallHS: 'High-Street', state: 'Karnataka' },
  'HFM': { storeName: 'HFM', mallHS: 'Mall', state: 'Telangana' },
  'HFQ': { storeName: 'HFQ', mallHS: 'Mall', state: 'Telangana' },
  'HFV': { storeName: 'HFV', mallHS: 'Mall', state: 'Telangana' },
  'HGM': { storeName: 'HGM', mallHS: '', state: '' },
  'HGQ': { storeName: 'HGQ', mallHS: '', state: '' },
  'HHM': { storeName: 'HHM', mallHS: '', state: '' },
  'HHP': { storeName: 'HHP', mallHS: 'High-Street', state: 'Punjab' },
  'HHV': { storeName: 'HHV', mallHS: 'High-Street', state: 'Telangana' },
  'HIM': { storeName: 'HIM', mallHS: '', state: '' },
  'HIQ': { storeName: 'HIQ', mallHS: 'Mall', state: 'Telangana' },
  'HJM': { storeName: 'HJM', mallHS: 'High-Street', state: 'Telangana' },
  'HKM': { storeName: 'HKM', mallHS: 'High-Street', state: 'Telangana' },
  'HKQ': { storeName: 'HKQ', mallHS: '', state: '' },
  'HKV': { storeName: 'HKV', mallHS: 'High-Street', state: 'Telangana' },
  'HLD': { storeName: 'HLD', mallHS: 'High-Street', state: 'Uttarakhand' },
  'HLM': { storeName: 'HLM', mallHS: '', state: '' },
  'HLQ': { storeName: 'HLQ', mallHS: '', state: '' },
  'HLV': { storeName: 'HLV', mallHS: 'High-Street', state: 'Telangana' },
  'HMQ': { storeName: 'HMQ', mallHS: '', state: '' },
  'HMV': { storeName: 'HMV', mallHS: 'High-Street', state: 'Telangana' },
  'HNG': { storeName: 'HNG', mallHS: 'High-Street', state: 'Rajasthan' },
  'HNM': { storeName: 'HNM', mallHS: 'High-Street', state: 'Telangana' },
  'HNQ': { storeName: 'HNQ', mallHS: 'High-Street', state: 'Telangana' },
  'HOM': { storeName: 'HOM', mallHS: 'Mall', state: 'Telangana' },
  'HOQ': { storeName: 'HOQ', mallHS: '', state: '' },
  'HPM': { storeName: 'HPM', mallHS: 'High-Street', state: 'Telangana' },
  'HPS': { storeName: 'HPS', mallHS: '', state: '' },
  'HPV': { storeName: 'HPV', mallHS: '', state: '' },
  'HRM': { storeName: 'HRM', mallHS: 'High-Street', state: 'Telangana' },
  'HRQ': { storeName: 'HRQ', mallHS: 'High-Street', state: 'Telangana' },
  'HRV': { storeName: 'HRV', mallHS: '', state: '' },
  'HSM': { storeName: 'HSM', mallHS: 'High-Street', state: 'Telangana' },
  'HSQ': { storeName: 'HSQ', mallHS: 'High-Street', state: 'Telangana' },
  'HSR': { storeName: 'HSR', mallHS: 'High-Street', state: 'Haryana' },
  'HSV': { storeName: 'HSV', mallHS: 'High-Street', state: 'Telangana' },
  'HTM': { storeName: 'HTM', mallHS: 'High-Street', state: 'Telangana' },
  'HTQ': { storeName: 'HTQ', mallHS: 'High-Street', state: 'Telangana' },
  'HTV': { storeName: 'HTV', mallHS: 'High-Street', state: 'Telangana' },
  'HUG': { storeName: 'HUG', mallHS: '', state: '' },
  'HUM': { storeName: 'HUM', mallHS: 'Mall', state: 'Karnataka' },
  'HUQ': { storeName: 'HUQ', mallHS: 'Mall', state: 'Karnataka' },
  'HUV': { storeName: 'HUV', mallHS: 'Mall', state: 'Karnataka' },
  'HVM': { storeName: 'HVM', mallHS: '', state: '' },
  'HVQ': { storeName: 'HVQ', mallHS: '', state: '' },
  'HWM': { storeName: 'HWM', mallHS: '', state: '' },
  'HYD': { storeName: 'HYD', mallHS: 'High-Street', state: 'Telangana' },
  'HYQ': { storeName: 'HYQ', mallHS: '', state: '' },
  'HZM': { storeName: 'HZM', mallHS: '', state: '' },
  'IBM': { storeName: 'IBM', mallHS: 'Mall', state: 'Maharashtra' },
  'IBQ': { storeName: 'IBQ', mallHS: 'Mall', state: 'Maharashtra' },
  'ICM': { storeName: 'ICM', mallHS: '', state: '' },
  'ICP': { storeName: 'ICP', mallHS: '', state: '' },
  'ICQ': { storeName: 'ICQ', mallHS: '', state: '' },
  'IDM': { storeName: 'IDM', mallHS: '', state: '' },
  'IDQ': { storeName: 'IDQ', mallHS: 'High-Street', state: 'Madhya Pradesh' },
  'IDV': { storeName: 'IDV', mallHS: 'High-Street', state: 'Madhya Pradesh' },
  'IFM': { storeName: 'IFM', mallHS: 'Mall', state: 'Maharashtra' },
  'IGM': { storeName: 'IGM', mallHS: '', state: '' },
  'IKV': { storeName: 'IKV', mallHS: 'Mall', state: 'Maharashtra' },
  'IMM': { storeName: 'IMM', mallHS: 'High-Street', state: 'Madhya Pradesh' },
  'IMP': { storeName: 'IMP', mallHS: 'High-Street', state: 'Manipur' },
  'IMQ': { storeName: 'IMQ', mallHS: 'Mall', state: 'Maharashtra' },
  'IMR': { storeName: 'IMR', mallHS: '', state: '' },
  'IMS': { storeName: 'IMS', mallHS: 'Mall', state: 'Maharashtra' },
  'INM': { storeName: 'INM', mallHS: '', state: '' },
  'IPM': { storeName: 'IPM', mallHS: '', state: '' },
  'IPQ': { storeName: 'IPQ', mallHS: 'High-Street', state: 'Manipur' },
  'ISM': { storeName: 'ISM', mallHS: 'High-Street', state: 'Madhya Pradesh' },
  'ISQ': { storeName: 'ISQ', mallHS: 'Mall', state: 'Madhya Pradesh' },
  'ISS': { storeName: 'ISS', mallHS: 'High-Street', state: 'Madhya Pradesh' },
  'ITM': { storeName: 'ITM', mallHS: 'High-Street', state: 'Arunachal Pradesh' },
  'ITN': { storeName: 'ITN', mallHS: 'High-Street', state: 'Arunachal Pradesh' },
  'ITQ': { storeName: 'ITQ', mallHS: 'High-Street', state: 'Arunachal Pradesh' },
  'ITS': { storeName: 'ITS', mallHS: 'Mall', state: 'Madhya Pradesh' },
  'JAM': { storeName: 'JAM', mallHS: 'High-Street', state: 'Punjab' },
  'JAQ': { storeName: 'JAQ', mallHS: 'High-Street', state: 'Gujarat' },
  'JBL': { storeName: 'JBL', mallHS: 'Mall', state: 'Madhya Pradesh' },
  'JBM': { storeName: 'JBM', mallHS: 'High-Street', state: 'Madhya Pradesh' },
  'JBQ': { storeName: 'JBQ', mallHS: 'Mall', state: 'Madhya Pradesh' },
  'JCM': { storeName: 'JCM', mallHS: 'High-Street', state: 'Rajasthan' },
  'JCQ': { storeName: 'JCQ', mallHS: 'High-Street', state: 'Rajasthan' },
  'JDC': { storeName: 'JDC', mallHS: '', state: '' },
  'JDH': { storeName: 'JDH', mallHS: 'High-Street', state: 'Rajasthan' },
  'JDM': { storeName: 'JDM', mallHS: 'High-Street', state: 'Rajasthan' },
  'JDV': { storeName: 'JDV', mallHS: 'High-Street', state: 'Jharkhand' },
  'JEM': { storeName: 'JEM', mallHS: '', state: '' },
  'JGM': { storeName: 'JGM', mallHS: 'High-Street', state: 'Assam' },
  'JGT': { storeName: 'JGT', mallHS: '', state: '' },
  'JHM': { storeName: 'JHM', mallHS: 'High-Street', state: 'Jharkhand' },
  'JHQ': { storeName: 'JHQ', mallHS: 'High-Street', state: 'Jharkhand' },
  'JHR': { storeName: 'JHR', mallHS: 'High-Street', state: 'Jharkhand' },
  'JHS': { storeName: 'JHS', mallHS: '', state: '' },
  'JHT': { storeName: 'JHT', mallHS: 'High-Street', state: 'Assam' },
  'JIM': { storeName: 'JIM', mallHS: 'High-Street', state: 'Rajasthan' },
  'JJM': { storeName: 'JJM', mallHS: '', state: '' },
  'JLG': { storeName: 'JLG', mallHS: '', state: '' },
  'JLH': { storeName: 'JLH', mallHS: '', state: '' },
  'JLQ': { storeName: 'JLQ', mallHS: 'High-Street', state: 'Punjab' },
  'JMD': { storeName: 'JMD', mallHS: 'High-Street', state: 'Punjab' },
  'JMM': { storeName: 'JMM', mallHS: 'High-Street', state: 'Gujarat' },
  'JMN': { storeName: 'JMN', mallHS: 'High-Street', state: 'Gujarat' },
  'JMQ': { storeName: 'JMQ', mallHS: 'Mall', state: 'Rajasthan' },
  'JMS': { storeName: 'JMS', mallHS: 'High-Street', state: 'Rajasthan' },
  'JMW': { storeName: 'JMW', mallHS: 'Mall', state: 'Jammu And Kashmir' },
  'JNQ': { storeName: 'JNQ', mallHS: 'Mall', state: 'Jharkhand' },
  'JOM': { storeName: 'JOM', mallHS: 'High-Street', state: 'Maharashtra' },
  'JPM': { storeName: 'JPM', mallHS: 'Mall', state: 'Rajasthan' },
  'JPQ': { storeName: 'JPQ', mallHS: 'High-Street', state: 'Rajasthan' },
  'JPR': { storeName: 'JPR', mallHS: 'High-Street', state: 'Rajasthan' },
  'JPS': { storeName: 'JPS', mallHS: 'High-Street', state: 'Rajasthan' },
  'JRM': { storeName: 'JRM', mallHS: 'High-Street', state: 'Rajasthan' },
  'JRQ': { storeName: 'JRQ', mallHS: 'Mall', state: 'Rajasthan' },
  'JRR': { storeName: 'JRR', mallHS: 'High-Street', state: 'Rajasthan' },
  'JSD': { storeName: 'JSD', mallHS: '', state: '' },
  'JSM': { storeName: 'JSM', mallHS: 'Mall', state: 'Rajasthan' },
  'JSQ': { storeName: 'JSQ', mallHS: 'Mall', state: 'Madhya Pradesh' },
  'JTQ': { storeName: 'JTQ', mallHS: 'High-Street', state: 'Rajasthan' },
  'JUM': { storeName: 'JUM', mallHS: '', state: '' },
  'JUQ': { storeName: 'JUQ', mallHS: 'Mall', state: 'Jammu And Kashmir' },
  'JWQ': { storeName: 'JWQ', mallHS: 'Mall', state: 'Rajasthan' },
  'JWT': { storeName: 'JWT', mallHS: 'Mall', state: 'Rajasthan' },
  'KAL': { storeName: 'KAL', mallHS: 'High-Street', state: 'Haryana' },
  'KAM': { storeName: 'KAM', mallHS: 'High-Street', state: 'Haryana' },
  'KCM': { storeName: 'KCM', mallHS: 'High-Street', state: 'Kerala' },
  'KCP': { storeName: 'KCP', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'KCQ': { storeName: 'KCQ', mallHS: 'High-Street', state: 'Kerala' },
  'KCV': { storeName: 'KCV', mallHS: 'Mall', state: 'Kerala' },
  'KDV': { storeName: 'KDV', mallHS: 'Shop-N-Shop', state: 'Maharashtra' },
  'KFM': { storeName: 'KFM', mallHS: '', state: '' },
  'KFQ': { storeName: 'KFQ', mallHS: '', state: '' },
  'KFS': { storeName: 'KFS', mallHS: '', state: '' },
  'KGR': { storeName: 'KGR', mallHS: 'High-Street', state: 'Maharashtra' },
  'KH5': { storeName: 'KH5', mallHS: '', state: '' },
  'KHM': { storeName: 'KHM', mallHS: 'High-Street', state: 'Maharashtra' },
  'KHQ': { storeName: 'KHQ', mallHS: '', state: '' },
  'KIQ': { storeName: 'KIQ', mallHS: 'High-Street', state: 'Telangana' },
  'KJM': { storeName: 'KJM', mallHS: '', state: '' },
  'KKM': { storeName: 'KKM', mallHS: '', state: '' },
  'KKV': { storeName: 'KKV', mallHS: 'High-Street', state: 'Andhra Pradesh' },
  'KL9': { storeName: 'KL9', mallHS: '', state: '' },
  'KLH': { storeName: 'KLH', mallHS: 'High-Street', state: 'Maharashtra' },
  'KLM': { storeName: 'KLM', mallHS: 'Mall', state: 'Kerala' },
  'KLQ': { storeName: 'KLQ', mallHS: 'Mall', state: 'Kerala' },
  'KLU': { storeName: 'KLU', mallHS: 'Mall', state: 'Kerala' },
  'KLV': { storeName: 'KLV', mallHS: 'High-Street', state: 'Maharashtra' },
  'KLY': { storeName: 'KLY', mallHS: 'Mall', state: 'Maharashtra' },
  'KMM': { storeName: 'KMM', mallHS: '', state: '' },
  'KMQ': { storeName: 'KMQ', mallHS: 'High-Street', state: 'Kerala' },
  'KNM': { storeName: 'KNM', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'KNP': { storeName: 'KNP', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'KNQ': { storeName: 'KNQ', mallHS: 'High-Street', state: 'Kerala' },
  'KNR': { storeName: 'KNR', mallHS: 'High-Street', state: 'Kerala' },
  'KOB': { storeName: 'KOB', mallHS: 'Mall', state: 'Chhattisgarh' },
  'KOL': { storeName: 'KOL', mallHS: 'High-Street', state: 'Kerala' },
  'KOM': { storeName: 'KOM', mallHS: 'High-Street', state: 'Rajasthan' },
  'KOO': { storeName: 'KOO', mallHS: 'High-Street', state: 'Rajasthan' },
  'KOQ': { storeName: 'KOQ', mallHS: 'High-Street', state: 'Kerala' },
  'KOT': { storeName: 'KOT', mallHS: 'High-Street', state: 'Kerala' },
  'KPM': { storeName: 'KPM', mallHS: 'Mall', state: 'Maharashtra' },
  'KPQ': { storeName: 'KPQ', mallHS: 'Mall', state: 'Maharashtra' },
  'KPS': { storeName: 'KPS', mallHS: 'Mall', state: 'Maharashtra' },
  'KRM': { storeName: 'KRM', mallHS: 'High-Street', state: 'Telangana' },
  'KRN': { storeName: 'KRN', mallHS: '', state: '' },
  'KRQ': { storeName: 'KRQ', mallHS: 'High-Street', state: 'Maharashtra' },
  'KRV': { storeName: 'KRV', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'KSG': { storeName: 'KSG', mallHS: '', state: '' },
  'KSQ': { storeName: 'KSQ', mallHS: 'High-Street', state: 'Andhra Pradesh' },
  'KST': { storeName: 'KST', mallHS: 'High-Street', state: 'Kerala' },
  'KWM': { storeName: 'KWM', mallHS: '', state: '' },
  'KYM': { storeName: 'KYM', mallHS: '', state: '' },
  'KZQ': { storeName: 'KZQ', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'LAQ': { storeName: 'LAQ', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'LAS': { storeName: 'LAS', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'LAV': { storeName: 'LAV', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'LBV': { storeName: 'LBV', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'LCM': { storeName: 'LCM', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'LCQ': { storeName: 'LCQ', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'LDH': { storeName: 'LDH', mallHS: 'High-Street', state: 'Punjab' },
  'LDM': { storeName: 'LDM', mallHS: 'High-Street', state: 'Punjab' },
  'LGQ': { storeName: 'LGQ', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'LHM': { storeName: 'LHM', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'LHQ': { storeName: 'LHQ', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'LIM': { storeName: 'LIM', mallHS: 'Mall', state: 'Maharashtra' },
  'LK9': { storeName: 'LK9', mallHS: '', state: '' },
  'LKM': { storeName: 'LKM', mallHS: 'High-Street', state: 'Maharashtra' },
  'LKQ': { storeName: 'LKQ', mallHS: 'High-Street', state: 'Maharashtra' },
  'LKR': { storeName: 'LKR', mallHS: 'High-Street', state: 'Maharashtra' },
  'LKS': { storeName: 'LKS', mallHS: '', state: '' },
  'LLM': { storeName: 'LLM', mallHS: '', state: '' },
  'LLQ': { storeName: 'LLQ', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'LLU': { storeName: 'LLU', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'LMD': { storeName: 'LMD', mallHS: 'Mall', state: 'Punjab' },
  'LMM': { storeName: 'LMM', mallHS: 'High-Street', state: 'Punjab' },
  'LMQ': { storeName: 'LMQ', mallHS: 'Mall', state: 'Punjab' },
  'LMS': { storeName: 'LMS', mallHS: 'High-Street', state: 'Punjab' },
  'LOM': { storeName: 'LOM', mallHS: 'Mall', state: 'Punjab' },
  'LPM': { storeName: 'LPM', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'LPQ': { storeName: 'LPQ', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'LPW': { storeName: 'LPW', mallHS: '', state: '' },
  'LSQ': { storeName: 'LSQ', mallHS: 'Mall', state: 'Punjab' },
  'LTM': { storeName: 'LTM', mallHS: 'High-Street', state: 'Maharashtra' },
  'LTQ': { storeName: 'LTQ', mallHS: '', state: '' },
  'LTR': { storeName: 'LTR', mallHS: 'High-Street', state: 'Maharashtra' },
  'LTV': { storeName: 'LTV', mallHS: '', state: '' },
  'LUH': { storeName: 'LUH', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'LUM': { storeName: 'LUM', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'LUP': { storeName: 'LUP', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'LWM': { storeName: 'LWM', mallHS: '', state: '' },
  'M1M': { storeName: 'M1M', mallHS: '', state: '' },
  'M1Q': { storeName: 'M1Q', mallHS: '', state: '' },
  'M2M': { storeName: 'M2M', mallHS: '', state: '' },
  'M4M': { storeName: 'M4M', mallHS: '', state: '' },
  'M5M': { storeName: 'M5M', mallHS: '', state: '' },
  'M6M': { storeName: 'M6M', mallHS: '', state: '' },
  'M9M': { storeName: 'M9M', mallHS: '', state: '' },
  'MAQ': { storeName: 'MAQ', mallHS: 'Airport', state: 'Maharashtra' },
  'MAS': { storeName: 'MAS', mallHS: 'Airport', state: 'Maharashtra' },
  'MASGUH': { storeName: 'MASGUH', mallHS: '', state: '' },
  'MBQ': { storeName: 'MBQ', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'MCA': { storeName: 'MCA', mallHS: 'Mall', state: 'Maharashtra' },
  'MCP': { storeName: 'MCP', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'MCQ': { storeName: 'MCQ', mallHS: 'Mall', state: 'Tamil Nadu' },
  'MCV': { storeName: 'MCV', mallHS: '', state: '' },
  'MDA': { storeName: 'MDA', mallHS: '', state: '' },
  'MDM': { storeName: 'MDM', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'MDN': { storeName: 'MDN', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'MDQ': { storeName: 'MDQ', mallHS: 'Airport', state: 'Maharashtra' },
  'MDR': { storeName: 'MDR', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'MDT': { storeName: 'MDT', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'MDY': { storeName: 'MDY', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'MEM': { storeName: 'MEM', mallHS: '', state: '' },
  'MEQ': { storeName: 'MEQ', mallHS: 'Mall', state: 'Tamil Nadu' },
  'MEX': { storeName: 'MEX', mallHS: 'Mall', state: 'Tamil Nadu' },
  'MFM': { storeName: 'MFM', mallHS: 'Mall', state: 'Tamil Nadu' },
  'MFQ': { storeName: 'MFQ', mallHS: 'Mall', state: 'Tamil Nadu' },
  'MFS': { storeName: 'MFS', mallHS: 'Mall', state: 'Tamil Nadu' },
  'MFV': { storeName: 'MFV', mallHS: 'Mall', state: 'Tamil Nadu' },
  'MGA': { storeName: 'MGA', mallHS: '', state: '' },
  'MGJBHJ': { storeName: 'MGJBHJ', mallHS: '', state: '' },
  'MGQ': { storeName: 'MGQ', mallHS: 'Mall', state: 'Karnataka' },
  'MGS': { storeName: 'MGS', mallHS: 'Mall', state: 'Karnataka' },
  'MGV': { storeName: 'MGV', mallHS: 'Mall', state: 'Karnataka' },
  'MHM': { storeName: 'MHM', mallHS: 'High-Street', state: 'Punjab' },
  'MHW': { storeName: 'MHW', mallHS: '', state: '' },
  'MIM': { storeName: 'MIM', mallHS: '', state: '' },
  'MIQ': { storeName: 'MIQ', mallHS: 'Airport', state: 'Maharashtra' },
  'MJM': { storeName: 'MJM', mallHS: '', state: '' },
  'MJQ': { storeName: 'MJQ', mallHS: 'Mall', state: 'Maharashtra' },
  'MK9': { storeName: 'MK9', mallHS: '', state: '' },
  'MKABDR': { storeName: 'MKABDR', mallHS: '', state: '' },
  'MKM': { storeName: 'MKM', mallHS: 'Mall', state: 'Tamil Nadu' },
  'MKQ': { storeName: 'MKQ', mallHS: 'Mall', state: 'Tamil Nadu' },
  'MKS': { storeName: 'MKS', mallHS: 'Mall', state: 'Tamil Nadu' },
  'MLD': { storeName: 'MLD', mallHS: 'High-Street', state: 'Maharashtra' },
  'MLP': { storeName: 'MLP', mallHS: '', state: '' },
  'MLQ': { storeName: 'MLQ', mallHS: '', state: '' },
  'MLV': { storeName: 'MLV', mallHS: '', state: '' },
  'MMC': { storeName: 'MMC', mallHS: 'Mall', state: 'Tamil Nadu' },
  'MMM': { storeName: 'MMM', mallHS: 'Mall', state: 'Maharashtra' },
  'MMPGWR': { storeName: 'MMPGWR', mallHS: '', state: '' },
  'MMQ': { storeName: 'MMQ', mallHS: 'Mall', state: 'Tamil Nadu' },
  'MMV': { storeName: 'MMV', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'MNC': { storeName: 'MNC', mallHS: '', state: '' },
  'MNM': { storeName: 'MNM', mallHS: 'High-Street', state: 'Karnataka' },
  'MNQ': { storeName: 'MNQ', mallHS: 'High-Street', state: 'Karnataka' },
  'MOB': { storeName: 'MOB', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'MOM': { storeName: 'MOM', mallHS: 'Mall', state: 'Karnataka' },
  'MOQ': { storeName: 'MOQ', mallHS: 'Mall', state: 'Karnataka' },
  'MOS': { storeName: 'MOS', mallHS: 'Mall', state: 'Karnataka' },
  'MP9': { storeName: 'MP9', mallHS: '', state: '' },
  'MPBFZK': { storeName: 'MPBFZK', mallHS: '', state: '' },
  'MPM': { storeName: 'MPM', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'MPQ': { storeName: 'MPQ', mallHS: '', state: '' },
  'MRC': { storeName: 'MRC', mallHS: 'Mall', state: 'Karnataka' },
  'MRM': { storeName: 'MRM', mallHS: 'Mall', state: 'Karnataka' },
  'MRQ': { storeName: 'MRQ', mallHS: 'Mall', state: 'Karnataka' },
  'MRT': { storeName: 'MRT', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'MSM': { storeName: 'MSM', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'MTM': { storeName: 'MTM', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'MTV': { storeName: 'MTV', mallHS: '', state: '' },
  'MUM': { storeName: 'MUM', mallHS: 'Mall', state: 'Tamil Nadu' },
  'MUS': { storeName: 'MUS', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'MVQ': { storeName: 'MVQ', mallHS: 'Mall', state: 'Tamil Nadu' },
  'MVR': { storeName: 'MVR', mallHS: 'Mall', state: 'Tamil Nadu' },
  'MVS': { storeName: 'MVS', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'MWBSLG': { storeName: 'MWBSLG', mallHS: '', state: '' },
  'MWM': { storeName: 'MWM', mallHS: '', state: '' },
  'MYQ': { storeName: 'MYQ', mallHS: 'High-Street', state: 'Karnataka' },
  'MYR': { storeName: 'MYR', mallHS: 'Mall', state: 'Karnataka' },
  'MZF': { storeName: 'MZF', mallHS: 'High-Street', state: 'Bihar' },
  'MZM': { storeName: 'MZM', mallHS: 'Mall', state: 'Bihar' },
  'MZP': { storeName: 'MZP', mallHS: '', state: '' },
  'NBM': { storeName: 'NBM', mallHS: '', state: '' },
  'NCL': { storeName: 'NCL', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'NCV': { storeName: 'NCV', mallHS: 'High-Street', state: 'Maharashtra' },
  'ND4': { storeName: 'ND4', mallHS: '', state: '' },
  'NDD': { storeName: 'NDD', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'NDL': { storeName: 'NDL', mallHS: '', state: '' },
  'NDO': { storeName: 'NDO', mallHS: '', state: '' },
  'NDQ': { storeName: 'NDQ', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'NDS': { storeName: 'NDS', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'NDV': { storeName: 'NDV', mallHS: '', state: '' },
  'NEM': { storeName: 'NEM', mallHS: 'Mall', state: 'Maharashtra' },
  'NES': { storeName: 'NES', mallHS: 'Mall', state: 'Maharashtra' },
  'NGM': { storeName: 'NGM', mallHS: 'High-Street', state: 'Maharashtra' },
  'NGP': { storeName: 'NGP', mallHS: 'High-Street', state: 'Maharashtra' },
  'NGR': { storeName: 'NGR', mallHS: '', state: '' },
  'NGS': { storeName: 'NGS', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'NGV': { storeName: 'NGV', mallHS: '', state: '' },
  'NHM': { storeName: 'NHM', mallHS: '', state: '' },
  'NHR': { storeName: 'NHR', mallHS: '', state: '' },
  'NIM': { storeName: 'NIM', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'NIQ': { storeName: 'NIQ', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'NKM': { storeName: 'NKM', mallHS: 'Mall', state: 'Maharashtra' },
  'NKQ': { storeName: 'NKQ', mallHS: 'Mall', state: 'Maharashtra' },
  'NKS': { storeName: 'NKS', mallHS: 'Mall', state: 'Maharashtra' },
  'NKV': { storeName: 'NKV', mallHS: 'Mall', state: 'Maharashtra' },
  'NLR': { storeName: 'NLR', mallHS: 'High-Street', state: 'Andhra Pradesh' },
  'NMM': { storeName: 'NMM', mallHS: '', state: '' },
  'NMV': { storeName: 'NMV', mallHS: '', state: '' },
  'NND': { storeName: 'NND', mallHS: 'High-Street', state: 'Maharashtra' },
  'NNM': { storeName: 'NNM', mallHS: 'High-Street', state: 'Maharashtra' },
  'NOM': { storeName: 'NOM', mallHS: '', state: '' },
  'NPM': { storeName: 'NPM', mallHS: 'High-Street', state: 'Maharashtra' },
  'NPQ': { storeName: 'NPQ', mallHS: 'High-Street', state: 'Maharashtra' },
  'NRM': { storeName: 'NRM', mallHS: '', state: '' },
  'NSK': { storeName: 'NSK', mallHS: 'High-Street', state: 'Maharashtra' },
  'NSM': { storeName: 'NSM', mallHS: 'High-Street', state: 'Maharashtra' },
  'NSP': { storeName: 'NSP', mallHS: '', state: '' },
  'NSQ': { storeName: 'NSQ', mallHS: 'High-Street', state: 'Maharashtra' },
  'NSS': { storeName: 'NSS', mallHS: '', state: '' },
  'NSV': { storeName: 'NSV', mallHS: 'High-Street', state: 'Maharashtra' },
  'NSZ': { storeName: 'NSZ', mallHS: '', state: '' },
  'NTM': { storeName: 'NTM', mallHS: '', state: '' },
  'NTP': { storeName: 'NTP', mallHS: 'Mall', state: 'Maharashtra' },
  'NTQ': { storeName: 'NTQ', mallHS: 'Mall', state: 'Maharashtra' },
  'NVV': { storeName: 'NVV', mallHS: 'High-Street', state: 'Maharashtra' },
  'NZB': { storeName: 'NZB', mallHS: 'High-Street', state: 'Telangana' },
  'NZM': { storeName: 'NZM', mallHS: '', state: '' },
  'NZQ': { storeName: 'NZQ', mallHS: 'High-Street', state: 'Telangana' },
  'OB9': { storeName: 'OB9', mallHS: '', state: '' },
  'OBM': { storeName: 'OBM', mallHS: '', state: '' },
  'OBQ': { storeName: 'OBQ', mallHS: '', state: '' },
  'OSQ': { storeName: 'OSQ', mallHS: '', state: '' },
  'P1Q': { storeName: 'P1Q', mallHS: '', state: '' },
  'PAH': { storeName: 'PAH', mallHS: '', state: '' },
  'PAM': { storeName: 'PAM', mallHS: 'Mall', state: 'Maharashtra' },
  'PBM': { storeName: 'PBM', mallHS: 'High-Street', state: 'Bihar' },
  'PBQ': { storeName: 'PBQ', mallHS: 'High-Street', state: 'Bihar' },
  'PBS': { storeName: 'PBS', mallHS: 'High-Street', state: 'Bihar' },
  'PCM': { storeName: 'PCM', mallHS: 'High-Street', state: 'Punjab' },
  'PDC': { storeName: 'PDC', mallHS: 'High-Street', state: 'Puducherry' },
  'PDM': { storeName: 'PDM', mallHS: 'High-Street', state: 'Puducherry' },
  'PDQ': { storeName: 'PDQ', mallHS: 'High-Street', state: 'Puducherry' },
  'PDV': { storeName: 'PDV', mallHS: '', state: '' },
  'PEL': { storeName: 'PEL', mallHS: '', state: '' },
  'PEM': { storeName: 'PEM', mallHS: 'Mall', state: 'Maharashtra' },
  'PFM': { storeName: 'PFM', mallHS: '', state: '' },
  'PFQ': { storeName: 'PFQ', mallHS: 'High-Street', state: 'Bihar' },
  'PGM': { storeName: 'PGM', mallHS: '', state: '' },
  'PGQ': { storeName: 'PGQ', mallHS: 'High-Street', state: 'Maharashtra' },
  'PGV': { storeName: 'PGV', mallHS: 'High-Street', state: 'Maharashtra' },
  'PHQ': { storeName: 'PHQ', mallHS: 'Mall', state: 'Maharashtra' },
  'PHX': { storeName: 'PHX', mallHS: 'Mall', state: 'Maharashtra' },
  'PIM': { storeName: 'PIM', mallHS: '', state: '' },
  'PJM': { storeName: 'PJM', mallHS: 'Mall', state: 'Maharashtra' },
  'PJQ': { storeName: 'PJQ', mallHS: 'High-Street', state: 'Maharashtra' },
  'PJV': { storeName: 'PJV', mallHS: '', state: '' },
  'PK9': { storeName: 'PK9', mallHS: '', state: '' },
  'PKB': { storeName: 'PKB', mallHS: '', state: '' },
  'PKM': { storeName: 'PKM', mallHS: 'Mall', state: 'Maharashtra' },
  'PKQ': { storeName: 'PKQ', mallHS: '', state: '' },
  'PKT': { storeName: 'PKT', mallHS: '', state: '' },
  'PKV': { storeName: 'PKV', mallHS: '', state: '' },
  'PLK': { storeName: 'PLK', mallHS: '', state: '' },
  'PLM': { storeName: 'PLM', mallHS: 'Mall', state: 'Bihar' },
  'PLQ': { storeName: 'PLQ', mallHS: 'Mall', state: 'Bihar' },
  'PLV': { storeName: 'PLV', mallHS: '', state: '' },
  'PMG': { storeName: 'PMG', mallHS: 'High-Street', state: 'Maharashtra' },
  'PMM': { storeName: 'PMM', mallHS: 'Mall', state: 'Maharashtra' },
  'PMP': { storeName: 'PMP', mallHS: 'High-Street', state: 'Maharashtra' },
  'PMQ': { storeName: 'PMQ', mallHS: 'Mall', state: 'Maharashtra' },
  'PMS': { storeName: 'PMS', mallHS: 'Mall', state: 'Maharashtra' },
  'PMW': { storeName: 'PMW', mallHS: '', state: '' },
  'PNM': { storeName: 'PNM', mallHS: 'High-Street', state: 'Bihar' },
  'POT': { storeName: 'POT', mallHS: 'Mall', state: 'Punjab' },
  'PPM': { storeName: 'PPM', mallHS: 'Mall', state: 'Maharashtra' },
  'PPQ': { storeName: 'PPQ', mallHS: '', state: '' },
  'PPT': { storeName: 'PPT', mallHS: '', state: '' },
  'PRB': { storeName: 'PRB', mallHS: 'High-Street', state: 'Bihar' },
  'PRM': { storeName: 'PRM', mallHS: '', state: '' },
  'PRQ': { storeName: 'PRQ', mallHS: '', state: '' },
  'PSM': { storeName: 'PSM', mallHS: 'Mall', state: 'Maharashtra' },
  'PSS': { storeName: 'PSS', mallHS: 'Mall', state: 'Maharashtra' },
  'PTA': { storeName: 'PTA', mallHS: 'High-Street', state: 'Punjab' },
  'PTM': { storeName: 'PTM', mallHS: 'High-Street', state: 'Punjab' },
  'PTN': { storeName: 'PTN', mallHS: 'High-Street', state: 'Bihar' },
  'PTQ': { storeName: 'PTQ', mallHS: 'High-Street', state: 'Punjab' },
  'PUK': { storeName: 'PUK', mallHS: '', state: '' },
  'PUM': { storeName: 'PUM', mallHS: '', state: '' },
  'PUN': { storeName: 'PUN', mallHS: 'High-Street', state: 'Maharashtra' },
  'PUT': { storeName: 'PUT', mallHS: '', state: '' },
  'PUV': { storeName: 'PUV', mallHS: '', state: '' },
  'PUZ': { storeName: 'PUZ', mallHS: '', state: '' },
  'PWM': { storeName: 'PWM', mallHS: '', state: '' },
  'PWQ': { storeName: 'PWQ', mallHS: 'Mall', state: 'Maharashtra' },
  'PZM': { storeName: 'PZM', mallHS: '', state: '' },
  'RBM': { storeName: 'RBM', mallHS: 'Mall', state: 'Karnataka' },
  'RCM': { storeName: 'RCM', mallHS: 'Mall', state: 'Chhattisgarh' },
  'RCQ': { storeName: 'RCQ', mallHS: 'High-Street', state: 'Jharkhand' },
  'RCV': { storeName: 'RCV', mallHS: 'Mall', state: 'Gujarat' },
  'RHM': { storeName: 'RHM', mallHS: 'High-Street', state: 'Jharkhand' },
  'RHV': { storeName: 'RHV', mallHS: '', state: '' },
  'RIC': { storeName: 'RIC', mallHS: 'Mall', state: 'Chhattisgarh' },
  'RIM': { storeName: 'RIM', mallHS: 'Mall', state: 'Chhattisgarh' },
  'RIP': { storeName: 'RIP', mallHS: 'Mall', state: 'Chhattisgarh' },
  'RIS': { storeName: 'RIS', mallHS: '', state: '' },
  'RIZ': { storeName: 'RIZ', mallHS: '', state: '' },
  'RJA': { storeName: 'RJA', mallHS: '', state: '' },
  'RJM': { storeName: 'RJM', mallHS: '', state: '' },
  'RJQ': { storeName: 'RJQ', mallHS: 'High-Street', state: 'Andhra Pradesh' },
  'RKQ': { storeName: 'RKQ', mallHS: '', state: '' },
  'RKT': { storeName: 'RKT', mallHS: 'High-Street', state: 'Gujarat' },
  'RKU': { storeName: 'RKU', mallHS: '', state: '' },
  'RMM': { storeName: 'RMM', mallHS: '', state: '' },
  'RMQ': { storeName: 'RMQ', mallHS: 'Mall', state: 'Chhattisgarh' },
  'RNC': { storeName: 'RNC', mallHS: 'High-Street', state: 'Jharkhand' },
  'RNM': { storeName: 'RNM', mallHS: 'Mall', state: 'Jharkhand' },
  'RNQ': { storeName: 'RNQ', mallHS: 'Mall', state: 'Jharkhand' },
  'RNR': { storeName: 'RNR', mallHS: '', state: '' },
  'RNS': { storeName: 'RNS', mallHS: 'Mall', state: 'Jharkhand' },
  'RPM': { storeName: 'RPM', mallHS: '', state: '' },
  'RRK': { storeName: 'RRK', mallHS: '', state: '' },
  'RTK': { storeName: 'RTK', mallHS: 'High-Street', state: 'Haryana' },
  'RTM': { storeName: 'RTM', mallHS: 'High-Street', state: 'Haryana' },
  'RTQ': { storeName: 'RTQ', mallHS: 'High-Street', state: 'Haryana' },
  'RUK': { storeName: 'RUK', mallHS: 'High-Street', state: 'Odisha' },
  'RWA': { storeName: 'RWA', mallHS: 'High-Street', state: 'Madhya Pradesh' },
  'RYM': { storeName: 'RYM', mallHS: 'High-Street', state: 'Gujarat' },
  'RYQ': { storeName: 'RYQ', mallHS: 'High-Street', state: 'Gujarat' },
  'RZM': { storeName: 'RZM', mallHS: '', state: '' },
  'SAC': { storeName: 'SAC', mallHS: 'Mall', state: 'West Bengal' },
  'SAL': { storeName: 'SAL', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'SAM': { storeName: 'SAM', mallHS: '', state: '' },
  'SAP': { storeName: 'SAP', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'SAQ': { storeName: 'SAQ', mallHS: 'Mall', state: 'West Bengal' },
  'SAV': { storeName: 'SAV', mallHS: 'Mall', state: 'Gujarat' },
  'SBP': { storeName: 'SBP', mallHS: 'High-Street', state: 'Odisha' },
  'SBQ': { storeName: 'SBQ', mallHS: '', state: '' },
  'SCM': { storeName: 'SCM', mallHS: 'Mall', state: 'Assam' },
  'SDM': { storeName: 'SDM', mallHS: '', state: '' },
  'SDV': { storeName: 'SDV', mallHS: '', state: '' },
  'SEL': { storeName: 'SEL', mallHS: '', state: '' },
  'SEM': { storeName: 'SEM', mallHS: '', state: '' },
  'SG5': { storeName: 'SG5', mallHS: '', state: '' },
  'SGM': { storeName: 'SGM', mallHS: 'Mall', state: 'West Bengal' },
  'SHG': { storeName: 'SHG', mallHS: '', state: '' },
  'SHL': { storeName: 'SHL', mallHS: 'High-Street', state: 'Meghalaya' },
  'SHM': { storeName: 'SHM', mallHS: '', state: '' },
  'SHV': { storeName: 'SHV', mallHS: 'Mall', state: 'Karnataka' },
  'SIL': { storeName: 'SIL', mallHS: 'Mall', state: 'West Bengal' },
  'SIM': { storeName: 'SIM', mallHS: 'High-Street', state: 'West Bengal' },
  'SIQ': { storeName: 'SIQ', mallHS: '', state: '' },
  'SIS': { storeName: 'SIS', mallHS: 'Mall', state: 'Assam' },
  'SKM': { storeName: 'SKM', mallHS: '', state: '' },
  'SKR': { storeName: 'SKR', mallHS: '', state: '' },
  'SLM': { storeName: 'SLM', mallHS: 'High-Street', state: 'Gujarat' },
  'SLP': { storeName: 'SLP', mallHS: '', state: '' },
  'SLQ': { storeName: 'SLQ', mallHS: 'High-Street', state: 'Gujarat' },
  'SMM': { storeName: 'SMM', mallHS: 'High-Street', state: 'Maharashtra' },
  'SNG': { storeName: 'SNG', mallHS: 'High-Street', state: 'Maharashtra' },
  'SNM': { storeName: 'SNM', mallHS: 'Mall', state: 'Maharashtra' },
  'SNQ': { storeName: 'SNQ', mallHS: 'Mall', state: 'Maharashtra' },
  'SOL': { storeName: 'SOL', mallHS: 'High-Street', state: 'Maharashtra' },
  'SOM': { storeName: 'SOM', mallHS: 'High-Street', state: 'Maharashtra' },
  'SON': { storeName: 'SON', mallHS: 'High-Street', state: 'Haryana' },
  'SOV': { storeName: 'SOV', mallHS: 'High-Street', state: 'Maharashtra' },
  'SPP': { storeName: 'SPP', mallHS: 'High-Street', state: 'Gujarat' },
  'SPQ': { storeName: 'SPQ', mallHS: 'High-Street', state: 'Gujarat' },
  'SRM': { storeName: 'SRM', mallHS: 'Mall', state: 'Gujarat' },
  'SRN': { storeName: 'SRN', mallHS: 'Mall', state: 'Jammu And Kashmir' },
  'SRQ': { storeName: 'SRQ', mallHS: 'Mall', state: 'Jammu And Kashmir' },
  'SRR': { storeName: 'SRR', mallHS: 'Mall', state: 'Gujarat' },
  'SRS': { storeName: 'SRS', mallHS: '', state: '' },
  'SRT': { storeName: 'SRT', mallHS: 'High-Street', state: 'Gujarat' },
  'SSQ': { storeName: 'SSQ', mallHS: '', state: '' },
  'STN': { storeName: 'STN', mallHS: 'High-Street', state: 'Madhya Pradesh' },
  'STV': { storeName: 'STV', mallHS: '', state: '' },
  'SVC': { storeName: 'SVC', mallHS: 'Mall', state: 'West Bengal' },
  'SVQ': { storeName: 'SVQ', mallHS: 'Mall', state: 'Gujarat' },
  'SWD': { storeName: 'SWD', mallHS: 'Mall', state: 'Maharashtra' },
  'SWM': { storeName: 'SWM', mallHS: 'High-Street', state: 'Gujarat' },
  'SZM': { storeName: 'SZM', mallHS: '', state: '' },
  'TAQ': { storeName: 'TAQ', mallHS: '', state: '' },
  'TCM': { storeName: 'TCM', mallHS: 'Mall', state: 'Kerala' },
  'TCS': { storeName: 'TCS', mallHS: 'Mall', state: 'Kerala' },
  'TCY': { storeName: 'TCY', mallHS: 'Mall', state: 'Kerala' },
  'TFS': { storeName: 'TFS', mallHS: 'High-Street', state: 'Kerala' },
  'THM': { storeName: 'THM', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'TIM': { storeName: 'TIM', mallHS: '', state: '' },
  'TIV': { storeName: 'TIV', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'TJM': { storeName: 'TJM', mallHS: '', state: '' },
  'TKM': { storeName: 'TKM', mallHS: 'Mall', state: 'Maharashtra' },
  'TKS': { storeName: 'TKS', mallHS: 'Mall', state: 'Maharashtra' },
  'TLM': { storeName: 'TLM', mallHS: 'Mall', state: 'Kerala' },
  'TLQ': { storeName: 'TLQ', mallHS: 'Mall', state: 'Kerala' },
  'TLU': { storeName: 'TLU', mallHS: 'Mall', state: 'Kerala' },
  'TMQ': { storeName: 'TMQ', mallHS: 'High-Street', state: 'Kerala' },
  'TMV': { storeName: 'TMV', mallHS: '', state: '' },
  'TNL': { storeName: 'TNL', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'TOV': { storeName: 'TOV', mallHS: '', state: '' },
  'TPM': { storeName: 'TPM', mallHS: 'High-Street', state: 'Kerala' },
  'TPT': { storeName: 'TPT', mallHS: '', state: '' },
  'TRC': { storeName: 'TRC', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'TRV': { storeName: 'TRV', mallHS: '', state: '' },
  'TSQ': { storeName: 'TSQ', mallHS: '', state: '' },
  'TSV': { storeName: 'TSV', mallHS: 'Mall', state: 'Karnataka' },
  'TSY': { storeName: 'TSY', mallHS: '', state: '' },
  'TTQ': { storeName: 'TTQ', mallHS: 'Mall', state: 'Kerala' },
  'TTS': { storeName: 'TTS', mallHS: 'Mall', state: 'Kerala' },
  'TTV': { storeName: 'TTV', mallHS: 'Mall', state: 'Kerala' },
  'TV4': { storeName: 'TV4', mallHS: '', state: '' },
  'TV9': { storeName: 'TV9', mallHS: '', state: '' },
  'TVL': { storeName: 'TVL', mallHS: 'High-Street', state: 'Kerala' },
  'TVM': { storeName: 'TVM', mallHS: 'Mall', state: 'Maharashtra' },
  'TVQ': { storeName: 'TVQ', mallHS: 'Mall', state: 'Maharashtra' },
  'TVS': { storeName: 'TVS', mallHS: 'Mall', state: 'Maharashtra' },
  'TZR': { storeName: 'TZR', mallHS: 'High-Street', state: 'Assam' },
  'UBM': { storeName: 'UBM', mallHS: 'Mall', state: 'Odisha' },
  'UBQ': { storeName: 'UBQ', mallHS: 'Mall', state: 'Odisha' },
  'UDM': { storeName: 'UDM', mallHS: '', state: '' },
  'UDP': { storeName: 'UDP', mallHS: '', state: '' },
  'UDQ': { storeName: 'UDQ', mallHS: 'Mall', state: 'Rajasthan' },
  'UDR': { storeName: 'UDR', mallHS: 'Mall', state: 'Rajasthan' },
  'ULS': { storeName: 'ULS', mallHS: 'Mall', state: 'Rajasthan' },
  'UPR': { storeName: 'UPR', mallHS: '', state: '' },
  'UTQ': { storeName: 'UTQ', mallHS: '', state: '' },
  'UUM': { storeName: 'UUM', mallHS: '', state: '' },
  'UUQ': { storeName: 'UUQ', mallHS: '', state: '' },
  'VAM': { storeName: 'VAM', mallHS: 'High-Street', state: 'Gujarat' },
  'VAP': { storeName: 'VAP', mallHS: 'High-Street', state: 'Gujarat' },
  'VAV': { storeName: 'VAV', mallHS: '', state: '' },
  'VBM': { storeName: 'VBM', mallHS: '', state: '' },
  'VBQ': { storeName: 'VBQ', mallHS: 'High-Street', state: 'Andhra Pradesh' },
  'VCM': { storeName: 'VCM', mallHS: '', state: '' },
  'VDM': { storeName: 'VDM', mallHS: '', state: '' },
  'VDS': { storeName: 'VDS', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'VGM': { storeName: 'VGM', mallHS: '', state: '' },
  'VGV': { storeName: 'VGV', mallHS: '', state: '' },
  'VIB': { storeName: 'VIB', mallHS: '', state: '' },
  'VIM': { storeName: 'VIM', mallHS: 'Mall', state: 'Maharashtra' },
  'VIQ': { storeName: 'VIQ', mallHS: 'Mall', state: 'Maharashtra' },
  'VJQ': { storeName: 'VJQ', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'VKM': { storeName: 'VKM', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'VLM': { storeName: 'VLM', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'VLQ': { storeName: 'VLQ', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'VLR': { storeName: 'VLR', mallHS: 'High-Street', state: 'Tamil Nadu' },
  'VNM': { storeName: 'VNM', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'VNS': { storeName: 'VNS', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'VSM': { storeName: 'VSM', mallHS: '', state: '' },
  'VSQ': { storeName: 'VSQ', mallHS: 'High-Street', state: 'Uttar Pradesh' },
  'VVP': { storeName: 'VVP', mallHS: 'Mall', state: 'Uttar Pradesh' },
  'VWD': { storeName: 'VWD', mallHS: 'High-Street', state: 'Andhra Pradesh' },
  'VWM': { storeName: 'VWM', mallHS: 'High-Street', state: 'Andhra Pradesh' },
  'VWP': { storeName: 'VWP', mallHS: 'Mall', state: 'Andhra Pradesh' },
  'VWQ': { storeName: 'VWQ', mallHS: 'High-Street', state: 'Andhra Pradesh' },
  'VZG': { storeName: 'VZG', mallHS: 'High-Street', state: 'Andhra Pradesh' },
  'VZM': { storeName: 'VZM', mallHS: 'High-Street', state: 'Andhra Pradesh' },
  'VZQ': { storeName: 'VZQ', mallHS: 'High-Street', state: 'Andhra Pradesh' },
  'VZV': { storeName: 'VZV', mallHS: '', state: '' },
  'WBM': { storeName: 'WBM', mallHS: '', state: '' },
  'WGAGOV': { storeName: 'WGAGOV', mallHS: '', state: '' },
  'WGJADV': { storeName: 'WGJADV', mallHS: '', state: '' },
  'WGJBVV': { storeName: 'WGJBVV', mallHS: '', state: '' },
  'WMHNTV': { storeName: 'WMHNTV', mallHS: '', state: '' },
  'WMHRMV': { storeName: 'WMHRMV', mallHS: '', state: '' },
  'WMPBMV': { storeName: 'WMPBMV', mallHS: '', state: '' },
  'WRM': { storeName: 'WRM', mallHS: 'High-Street', state: 'Telangana' },
  'WSQ': { storeName: 'WSQ', mallHS: '', state: '' },
  'WTNMVV': { storeName: 'WTNMVV', mallHS: '', state: '' },
  'WTNPKV': { storeName: 'WTNPKV', mallHS: '', state: '' },
  'YMM': { storeName: 'YMM', mallHS: 'High-Street', state: 'Haryana' },
  'YMN': { storeName: 'YMN', mallHS: 'High-Street', state: 'Haryana' },
  'ZCQ': { storeName: 'ZCQ', mallHS: 'Mall', state: 'Punjab' },
  'ZRM': { storeName: 'ZRM', mallHS: '', state: '' },
};
